### ISSUE TITLE
conflict with unprompted extension

### ISSUE THREAD

**Issue by gsgoldma** [thygate/stable-diffusion-webui-depthmap-script#100]
Not sure if you're aware, but there seems to be some conflict with a lib folder that is used in both. take a look here https://github.com/ThereforeGames/unprompted/issues/25

not implying that you should do anything about it. just making aware, there may be more conflicts with other extensions in the future with this kind of issue

**Comment by graemeniedermayer** [comment]
That looks like a scoping issue with all auto1111 extensions hopefully that gets patched because that will make maintaining extension quite difficult.

**Comment by thygate** [comment]
I kept the structure for the LeRes code from the BoostingMonocularDepth repo, I knew this might be an issue, but had not encountered any collisions myself. I might refactor it in some future version.

@graemeniedermayer Thanks for following up
