### ISSUE TITLE
Missing dropdowns on v0.1.1

### ISSUE THREAD

**Issue by luebee** [thygate/stable-diffusion-webui-depthmap-script#11]
After installing v0.1.1 the interface seems to be missing dropdowns for selecting models, Compute on and Combine axis in txt2img and img2img

![Missing dropdown](https://user-images.githubusercontent.com/70564774/200095208-67ee2aec-c0a4-4c44-96e2-3274cd6f69d1.JPG)

**Comment by thygate** [comment]
Try clicking the button `Reload custom script bodies` at the bottom of the settings tab, and try refreshing the page otherwise.

**Comment by luebee** [comment]
Unfortunately the issue is still persisting after reloading scripts and restarting gradio interface, i even did clean reinstalls of both the web UI and depthmap script without any luck

**Comment by luebee** [comment]
It still functions but im stuck using dpt_large by default and in console appears to only download the single model
![SDConsole2](https://user-images.githubusercontent.com/70564774/200098139-fa71783f-9508-4ab5-9ebb-2dde87793f82.JPG)

**Comment by thygate** [comment]
have you tried force refreshing the web page ?

There have been issues at times with the webui where scripts don't update properly, did you pull the most recent version of the webui ?

**Comment by luebee** [comment]
yes refreshing didnt work and i did git pull the latest version of the web UI

**Comment by thygate** [comment]
i'm about to push a new version of the script, v0.1.2, hopefully this solves the issue you're having..

**Comment by djkacevedo** [comment]
I've got 0.1.2 installed, and I have the same issue.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/5597220/200100196-77697899-9270-45c0-9d78-1e2475ddf3ff.png">

**Comment by djkacevedo** [comment]
I looked at the script. Visible is set to false on a few of the options. Changing to true to fixes it.

**Comment by thygate** [comment]
You're absolutely right, the invisible controls in your screenshot are the ones that have the visibility set to false.
This totally escaped me, it was always showing on my webui build (i'm not current), so I gather a newer build is implementing the visibility. 
Thanks for catching this, I'll release v0.1.3 in a few moments with this fix.
