### ISSUE TITLE
Error computing request?

### ISSUE THREAD

**Issue by sgtdingo** [thygate/stable-diffusion-webui-depthmap-script#12]
Hello, I have installed the script as described but each time I run it I error out after image generation. Could anyone help me with this issue? Copy-pasted below. Thank you!

100%|██████████████████████████████████████████████████████████████████████████████████| 65/65 [03:03<00:00,  2.82s/it]
Total progress: 740it [29:42,  2.85s/it]
DepthMap v0.1.3
device: cuda
Loading midas model weights ..
./models/midas/dpt_hybrid-midas-501f0c75.pt
Computing depthmap(s) ..
Error completing request
Arguments: ('A trainer training many loud kittens in his shitbox apartment', '', 'None', 'None', 65, 4, True, False, 1, 1, 8.5, -1.0, -1.0, 0, 0, 0, False, 512, 832, False, 0.7, 0, 0, 1, 1, 384, 0, True, True, False, 1, False, False, False, None, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "C:\Users\carte\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\carte\stable-diffusion-webui\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "C:\Users\carte\stable-diffusion-webui\modules\txt2img.py", line 45, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\carte\stable-diffusion-webui\modules\scripts.py", line 282, in run
    processed = script.run(p, *script_args)
  File "C:\Users\carte\stable-diffusion-webui\scripts\depthmap.py", line 206, in run
    out = np.zeros(depth.shape, dtype=depth.type)
AttributeError: 'numpy.ndarray' object has no attribute 'type'

**Comment by thygate** [comment]
what commandline arguments are you running with ?

**Comment by sgtdingo** [comment]
--medvram --no-half --precision full --opt-split-attention

**Comment by thygate** [comment]
> --medvram --no-half --precision full --opt-split-attention

Could you try again without any command line arguments, see if that fixed the problem, so i can narrow it down.

**Comment by sgtdingo** [comment]
I will give that a try, although the command line arguments are there
because I'm running a 1650Ti which doesn't support half precision, so
without them I tend to get out of memory errors.
Thanks!

**Comment by sgtdingo** [comment]
Just remembered that the other reason for the command line arguments is that without them I only get a green square (consequence of the Nvidia card I'm using)

**Comment by sgtdingo** [comment]
Tried with no commandline arguments and got the same results: 

Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:49<00:00,  2.61s/it]
DepthMap v0.1.3
device: cuda
Loading midas model weights ..
./models/midas/dpt_large-midas-2f21e586.pt
Computing depthmap(s) ..
Error completing request
Arguments: ('test', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 1, 0, 384, 0, True, True, True, 1, False, False, False, None, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "C:\Users\carte\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\carte\stable-diffusion-webui\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "C:\Users\carte\stable-diffusion-webui\modules\txt2img.py", line 45, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\carte\stable-diffusion-webui\modules\scripts.py", line 282, in run
    processed = script.run(p, *script_args)
  File "C:\Users\carte\stable-diffusion-webui\scripts\depthmap.py", line 206, in run
    out = np.zeros(depth.shape, dtype=depth.type)
AttributeError: 'numpy.ndarray' object has no attribute 'type'

**Comment by thygate** [comment]
The Error occurs on a line that actually just creates an empty depth map because of the preceding check that fails.
I've fixed the problem on that line, but it just outputs a empty/black depthmap .

I've temporarily changed the code to skip that check, which might lead to a division by zero error..

Could you try pulling the current script, and try again ?

**Comment by thygate** [comment]
Did you also try selecting CPU for compute in the script options ?

**Comment by sgtdingo** [comment]
I will give it another go in a second, thanks!

**Comment by sgtdingo** [comment]
PERFECT! It's working for me now. Thank you so much! Now to play around with some depthmap fun!

**Comment by thygate** [comment]
Is it working in CPU mode or both now ?

If this fixed the issue I will change the mentioned check to a different method.

**Comment by sgtdingo** [comment]
In CPU mode only at this time.

**Comment by sgtdingo** [comment]
I appreciate your working with me to conquer this bug. Thank you!

**Comment by thygate** [comment]
GPU mode outputs a black depthmap now ? Or throwing any errors ?

**Comment by sgtdingo** [comment]
Just outputting a black depthmap now in GPU mode.

**Comment by sgtdingo** [comment]
No error messages.

**Comment by thygate** [comment]
The check that always fails for you when computing on GPU using a 1650Ti, is actually there to prevent a divide by zero error, or NaN results when the MiDaS network outputs an empty image. 

So the MiDaS network is always outputting an empty image when you run on GPU, you could create an issue on their repo if you want to follow this up further. 

Since you can get it working in CPU compute mode, I'm considering this issue solved.

**Comment by thygate** [comment]
I spent some time going through the webui code and some other plugins code to find references to the no-half and precision-full arguments and learned a few new things along the way, i'm pretty new to pytorch, and python myself.

I've released a new version v0.1.4 of the script that implements the `-no-half` switch, so hopefully it now also works on cards that don't support half precision mode like your (mobile?) 1650Ti ..

Could you test the new script on gpu and cpu and tell me if it's now working in gpu mode too ?
Thanks!

**Comment by sgtdingo** [comment]
Unfortunately with the new version of the script I am now getting the following error:

Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\carte\stable-diffusion-webui\modules\scripts.py", line 153, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "C:\Users\carte\stable-diffusion-webui\scripts\depthmap.py", line 70
    <title>stable-diffusion-webui-depthmap-script/depthmap.py at main · thygate/stable-diffusion-webui-depthmap-script</title>
                                                                      ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by thygate** [comment]
Seems like you downloaded the file as html again ?

When viewing a file on github, like the `depthmap.py` in this repository, there's a button 'RAW' on the top right of the code, click that to get the raw file. 

https://github.com/thygate/stable-diffusion-webui-depthmap-script/raw/main/depthmap.py

**Comment by thygate** [comment]
Seems like you downloaded the file as html ?

direct link :
https://github.com/thygate/stable-diffusion-webui-depthmap-script/raw/main/depthmap.py

**Comment by sgtdingo** [comment]
You are correct. Rookie mistake on my part. 
You fixed it! Working on both GPU and CPU, now.

**Comment by thygate** [comment]
Easy mistake I've been there, great! thanks for taking the time to test it. I can now update the readme and close this issue.

**Comment by ashoklathwal** [comment]
https://wealthquint.com/fix-stable-diffusion-error-completing-request-61801/
