### ISSUE TITLE
Extension Not Showing

### ISSUE THREAD

**Issue by Ashflre** [thygate/stable-diffusion-webui-depthmap-script#124]
When I install an extension I press "Apply and restart UI" and once it's done refreshing the extension does not show up. How do I fix this?

I'm pretty sure it should be in between "Train" and "Settings"
![Extension Not There](https://user-images.githubusercontent.com/126562753/221814123-f57b00f4-7f70-4547-9cdf-845196f7d450.jpg)

**Comment by thygate** [comment]
check the console for any error output

**Comment by Ashflre** [comment]
Where do I find the console? And how do I restart the backend?

**Comment by Ubermeisters** [comment]
> When I install an extension I press "Apply and restart UI" and once it's done refreshing the extension does not show up. How do I fix this?
> 
> I'm pretty sure it should be in between "Train" and "Settings" ![Extension Not There](https://user-images.githubusercontent.com/126562753/221814123-f57b00f4-7f70-4547-9cdf-845196f7d450.jpg)

I am experiencing the same issue. Console is the command prompt window that pops up when you run the .bat file. Console is an old term for a computer used to interface with a server I think. Restarting the 'backend" is the same as saying go into settings and reloading the things that you see loading in the console at startup. the GUI will go blank and say there is no connection until the console says you are good to go again.

I had an error that wasn't allowing ddetailer to load (whatever that is, idk) so I am nuking my venv folder and trying a "fresh install" of the virtual environment, in the hopes that it fixes things. Ill update here when I know.

**Comment by Ashflre** [comment]
After I managed to delete it and reinstall it worked. Thank you so much for the solution.
