### ISSUE TITLE
SyntaxError: invalid character '·'

### ISSUE THREAD

**Issue by Mousewrites** [thygate/stable-diffusion-webui-depthmap-script#13]
Hello! I am getting this error running the script on Auto11111's webui. I just found this script this morning, so i haven't run it successfully yet. I was able to clone the midas repo stuff as instructed.

```
Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\Users\Linds\stable-diffusion-webui\modules\scripts.py", line 169, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "C:\Users\Linds\stable-diffusion-webui\scripts\depthmap.py", line 70
    <title>stable-diffusion-webui-depthmap-script/depthmap.py at main · thygate/stable-diffusion-webui-depthmap-script</title>
                                                                      ^
SyntaxError: invalid character '·' (U+00B7)
```

Have I bunged something up?

**Comment by thygate** [comment]
Looks like you downloaded the markup/html version of the `depthmap.py` script ?

Re-download the script using this url :
https://raw.githubusercontent.com/thygate/stable-diffusion-webui-depthmap-script/main/depthmap.py

**Comment by Mousewrites** [comment]
Yup, that fixed it. I had right clicked on the depthmap.py file and saved as. 

Thank you so much for this. I've been salivating for somebody to get the MiDAS stuff into Automatic1111. <3

**Comment by thygate** [comment]
> Yup, that fixed it. I had right clicked on the depthmap.py file and saved as.
> 
> Thank you so much for this. I've been salivating for somebody to get the MiDAS stuff into Automatic1111. <3

You're welcome, have fun, and feel free to comment & share in the discussions section.
