### ISSUE TITLE
I have no depth tab

### ISSUE THREAD

**Issue by lolalilelu** [thygate/stable-diffusion-webui-depthmap-script#148]
Installed the extension, both through URL and the 'available' tab, the extension is updated, however I have no depth tab and I cannot find it anywhere.
![image](https://user-images.githubusercontent.com/128918155/227726585-1def886b-4df6-4b64-aeaf-8798ec2fd102.png)
![image](https://user-images.githubusercontent.com/128918155/227726617-ea83dad3-13f1-40b1-8e7b-522bdbdfe91d.png)

**Comment by thygate** [comment]
Please check the console for errors.

**Comment by lolalilelu** [comment]
Thanks for the quick response, I did the old trick of turning it off and on again and now it works. I had restarted it a few times, so I'm not sure what was different this time around. Thanks again!

**Comment by thygate** [comment]
I should update the README to say to restart the backend as this has come up before.. Anyway, great you got it working, have fun!
