### ISSUE TITLE
Grayscale and RGBA images crash batch processing.

### ISSUE THREAD

**Issue by enn-nafnlaus** [thygate/stable-diffusion-webui-depthmap-script#157]
Right what it says on the tin.  Have a RGBA or grayscale PNG in your batch dir and try to run it.  You crash out processing, require an AUTOMATIC1111 restart to be able to get back to processing again.  

(People often don't realize when an image is RGBA as opposed to RGB, or expect that a grayscale image might cause problems)

Best solution: convert them to RGB.
Fair solution: just skip them, report an error, and continue on.

**Comment by thygate** [comment]
A stack trace would be helpful.

**Comment by enn-nafnlaus** [comment]
I should have a crash before I go to bed due to the memory leak (#156), so rather than interrupt my current batch run, I'll just wait for it to crash out again, and try to remember to insert an RGBA or greyscale image in then.  It's easy enough to do, as the depth masks themselves are greyscale - all you have to do is copy one into the batch directory..

**Comment by enn-nafnlaus** [comment]
Oh huh, it already crashed out  :)  Okay, here you go!

> To create a public link, set `share=True` in `launch()`.
> Startup time: 142.0s (import gradio: 2.0s, import ldm: 27.5s, other imports: 7.8s, list extensions: 6.6s, list SD models: 3.8s, setup codeformer: 0.6s, load scripts: 25.9s, load SD checkpoint: 49.7s, create ui: 16.9s, gradio launch: 0.8s, scripts app_started_callback: 0.1s).
> 
> DepthMap v0.3.8
> device: cuda
> Loading model weights from  ./models/midas/dpt_large-midas-2f21e586.pt
> initialize network with normal
> loading the model from ./models/pix2pix/latest_net_G.pth
> Computing depthmap(s) ..
>   0%|                                                                                                                                                                                                           | 0/42 [00:00<?, ?it/s]
> 
>   0%|                                                                                                                                                                                                           | 0/42 [00:00<?, ?it/s]
> Error completing request
> Arguments: (2, None, None, '/path/to/stable-diffusion-webui/outputs/txt2img-images/2023-03-31/batch_in', '/path/to/stable-diffusion-webui/outputs/txt2img-images/2023-03-31/batch_out', 0, 3, 1920, 1080, True, False, True, True, True, False, False, 1, False, False, False, 2.5, 4, 0, False, 0, 1, True, True, 'u2net', False, False, False, 0, 2) {}
> Traceback (most recent call last):
>   File "/path/to/AUTOMATIC1111/stable-diffusion-webui/modules/call_queue.py", line 56, in f
>     res = list(func(*args, **kwargs))
>   File "/path/to/AUTOMATIC1111/stable-diffusion-webui/modules/call_queue.py", line 37, in f
>     res = func(*args, **kwargs)
>   File "/path/to/AUTOMATIC1111/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 1158, in run_generate
>     outputs, mesh_fi = run_depthmap(None, outpath, imageArr, imageNameArr, compute_device, model_type, net_width, net_height, match_size, invert_depth, boost, save_depth, show_depth, show_heat, combine_output, combine_output_axis, gen_stereo, gen_stereotb, gen_anaglyph, stereo_divergence, stereo_fill, stereo_balance, clipdepth, clipthreshold_far, clipthreshold_near, inpaint, inpaint_vids, fnExt, vid_ssaa, background_removal, background_removed_images, save_background_removal_masks, False)
>   File "/path/to/AUTOMATIC1111/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 347, in run_depthmap
>     img = cv2.cvtColor(np.asarray(inputimages[count]), cv2.COLOR_BGR2RGB) / 255.0
> cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> > Unsupported depth of input image:
> >     'VDepth::contains(depth)'
> > where
> >     'depth' is 4 (CV_32S)
> 
> 
> Traceback (most recent call last):
>   File "/path/to/AUTOMATIC1111/stable-diffusion-webui/venv/lib64/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/path/to/AUTOMATIC1111/stable-diffusion-webui/venv/lib64/python3.10/site-packages/gradio/blocks.py", line 1018, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "/path/to/AUTOMATIC1111/stable-diffusion-webui/venv/lib64/python3.10/site-packages/gradio/blocks.py", line 935, in postprocess_data
>     if predictions[i] is components._Keywords.FINISHED_ITERATING:
> IndexError: tuple index out of range
>

**Comment by thygate** [comment]
I cannot recreate this error with a 32bpp 4 channel PNG .. Post an image that is giving you trouble so I can replicate the problem.

**Comment by enn-nafnlaus** [comment]
> I cannot recreate this error with a 32bpp 4 channel PNG .. Post an image that is giving you trouble so I can replicate the problem.

I literally just grabbed the first output depthmap I encountered (since they're greyscale).  Here:

![00000-3767897183-0000](https://user-images.githubusercontent.com/116288799/230175186-b722aff5-8d41-4412-b0f5-0342f8a0de5b.png)

**Comment by enn-nafnlaus** [comment]
In case it matters: 

Tab: "Batch from directory"
Net width: 1920
Net height: 1080
Model: dpt_large_384 (midas 3.0)
Match input size
Generate 3D inpainted mesh
Generate 4 demo videos

Everything else is defaults.

**Comment by thygate** [comment]
should be fixed

**Comment by enn-nafnlaus** [comment]
> should be fixed

Excellent!  Will try it when I need to restart next due to my next scheduled crash  :)

**Comment by enn-nafnlaus** [comment]
Verified fixed.  Well done!  :)
