### ISSUE TITLE
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'all_prompts'

### ISSUE THREAD

**Issue by ivangusto** [thygate/stable-diffusion-webui-depthmap-script#16]
Hi, I am having an issue trying to generate the depth map inside webui. I am using anaconda prompt in a custom separate environment with stable-diffusion webui installed and working. The error happens after it loads in the midas model weights and try to start computing depthmap. Is there something I missed? Thanks in advance. 

`Traceback (most recent call last):
  File "D:\Super_Stable_Diffusion\stable-diffusion-webui\modules\ui.py", line 186, in f
    res = list(func(*args, **kwargs))
  File "D:\Super_Stable_Diffusion\stable-diffusion-webui\webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "D:\Super_Stable_Diffusion\stable-diffusion-webui\modules\txt2img.py", line 40, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\Super_Stable_Diffusion\stable-diffusion-webui\modules\scripts.py", line 159, in run
    processed = script.run(p, *script_args)
  File "D:\Super_Stable_Diffusion\stable-diffusion-webui\scripts\depthmap_2.py", line 175, in run
    info = create_infotext(p, p.all_prompts, p.all_seeds, p.all_subseeds, "", 0, 0)
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'all_prompts'`

**Comment by thygate** [comment]
The StableDiffusionProcessingTxt2Img object is passed as argument to the script run function and should contain an attribute all_prompts containing all the prompts ..

Are you running with any specific settings that would not add this information, or any other modifications or extensions that could interfere with storing the prompts in the images ?

For now you could replace that line with this to get it working for you :
```
info = None
```

But I would like to know the reason why it's not passing in all_prompts so I can account for it in the script, so if there's any other info/settings you know of that might be causing this, please share.

**Comment by thygate** [comment]
Should be solved in v0.1.7, can you verify ?

**Comment by ivangusto** [comment]
> Should be solved in v0.1.7, can you verify ?

It works like a charm! Thank you
