### ISSUE TITLE
Low VRAM after running

### ISSUE THREAD

**Issue by hacker1024** [thygate/stable-diffusion-webui-depthmap-script#17]
My 2GB GPU is capable of running Stable Diffusion.
This script's GPU support also works just fine after generating an image.

After using the script, however, subsequent Stable Diffusion runs fail due to VRAM unavailability. Is the model persisting in VRAM after use? If so, can it be freed between uses?

**Comment by thygate** [comment]
Hi, thanks for reporting. I'm still pretty new at python and was assuming everything would be garbage collected when it goes out of scope, including the pytorch model in vram.

Some googling seems to confirm this. (https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management)

I'm looking into it further ..

**Comment by thygate** [comment]
I will specifically delete the model before returning from the script in the next version, so we don't need to wait for the GC to kick in.

**Comment by thygate** [comment]
In v0.1.7 the model is deleted (freed) at the end of the script now, did that fix the problem ?

**Comment by Lektro9** [comment]
I had a similar issue while using your script in txt2img on a 8gb vram card yesterday (just out of memory error and couldnt generate any images anymore). Just tested it with v1.7 and it does not seem to happen anymore.

**Comment by thygate** [comment]
I'm closing this issue as the problem seems to be solved.
