### ISSUE TITLE
Can we run this on existing/original images?

### ISSUE THREAD

**Issue by bbecausereasonss** [thygate/stable-diffusion-webui-depthmap-script#18]
Say I have an existing image (I don't want to change at all through IMG2IMG) can I still use this?

**Comment by thygate** [comment]
Yes, you can use img2img and set denoising strength to 0, which will effectively skip stable diffusion and run the depthmap script on the original.

**Comment by thygate** [comment]
Yes, you will have to set the correct size and need to select `Crop and resize` instead of `Just resize` when the input image resolution does not match the set size perfectly.
