### ISSUE TITLE
A bit confused.

### ISSUE THREAD

**Issue by HanshustlerHHHH** [thygate/stable-diffusion-webui-depthmap-script#187]
I followed a tutorial on youtube 

i created the inpainted mesh 
and tried it like you write here

"To view the 3D-inpainted mesh in blender:

import the PLY file
Set camera to origin (0, 0, 0) and pointing up to align it with the mesh
adjust camera FOV to match the mesh
Add a 'Color Attribute' Node and connect it to the shader color input" 

and then i saw that i got an .obj file 

why? theres nothin in the changelog about that. 

i m confused now haha because i ve no texture in blender

**Comment by thygate** [comment]
From the Changelog : 

wavefront obj output support for inpainted mesh (enabled in settings)
...
default output format is now obj for inpainted mesh and simple mesh


If you still want the PLY, enable it in settings.

Otherwise there is NO DIFFERENCE between the OBJ and PLY except for the format, blender will read both just fine.

Also, this does not generate a textured mesh, but a mesh with vertex colors. So create a color attrib node connected to your shader as per the instructions.

**Comment by devingfx** [comment]
Hi!
Do you have any working exemple of shader nodes setting?
I have got only a black color blob with 9 millions vertices and 37 million face quite unusable...
Is it creating a vertex/face for each original picture pixel ?

**Comment by thygate** [comment]
@devingfx 
Both options to generate meshes output a non-textured (no uv's) mesh with per vertex colors. 
In blender shader nodes, use a "Color Attribute" node (Input/Color Attribute) to get the vertex color.
So for example connect the Color output of this node into an Emission shader and connect that output to material output.

I'm not sure for the inpainted mesh but I do believe both options generate one vertex per pixel in the original image, with some upper bound. Lower the resolution on your image to get a smaller set, or decimate the set in blender.

**Comment by devingfx** [comment]
Hi! Thx for this instant reply :)
I didn't figure out the double importer in Blender... I used `Wavefront (.obj) experimental` I'll try the other one...
For the shader it's exactly what I did tough :/

**Comment by thygate** [comment]
@devingfx If Wavefront OBJ keeps giving you problems, you can try to enable PLY file output in A1111's Settings/Depthmap.

**Comment by devingfx** [comment]
I tested both OBJ import and I couldn't get any colors. (opening the "spreadsheet" view in blender don't show any color attribute in the vertices/face data)
PLY import is working, I get the colors with the color attribute...

I'm using a v3.2 of Blender is this an issue?

**Comment by thygate** [comment]
@devingfx well i'm not sure, storing vertex colors in wavefront obj is outside of the spec, they way I export it (v x,y,z,r,g,b) is how blender itself outputs a OBJ file with vertex colors. It was working for me and others in the past.

**Comment by devingfx** [comment]
Oki d'oki... I'll use PLY... thanks by the way to had took time to answer questions !

PS: If OBJ is not made for this use case + you did retro-ingeneering on the data (out of the spec), IMHO this format should not be the default one though... Just stick to the PLY format by default !

**Comment by thygate** [comment]
Yes, binary PLY should be the default output format.

**Comment by devingfx** [comment]
> It was changed to OBJ at some point because some users complained...

You should not change to please complainers! Do it your way and invite to fork ;)
(This is said with love)
