### ISSUE TITLE
Check this out (GUI)

### ISSUE THREAD

**Issue by bbecausereasonss** [thygate/stable-diffusion-webui-depthmap-script#19]
Found this GUI, but the toolkit (links do not work).

Any ideas how to get this running?

https://github.com/ilharp/depth-estimate-gui

**Comment by thygate** [comment]
No, please open an issue on said repository.

I'm closing this issue since it's not related to this repository.

Please feel free to start a discussion to ask questions not related to this repo, to comment, or share !

Thanks.
