### ISSUE TITLE
Last installation of AUTOMATIC1111 does not install this extension

### ISSUE THREAD

**Issue by pepebc** [thygate/stable-diffusion-webui-depthmap-script#208]
Last installation of AUTOMATIC1111 does not install this extension. Prompt:

Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on pepe user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################
Requirement already satisfied: wheel in ./venv/lib/python3.11/site-packages (0.40.0)

################################################################
Launching launch.py...
################################################################
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing requirements
Error running install.py for extension /mnt/DATOS/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script.
Command: "/mnt/DATOS/stable-diffusion-webui/venv/bin/python3" "/mnt/DATOS/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/install.py"
Error code: 1
stdout: Installing rembg requirement for depthmap script

stderr: Traceback (most recent call last):
  File "/mnt/DATOS/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/install.py", line 19, in <module>
    launch.run_pip("install rembg", "rembg requirement for depthmap script")
  File "/mnt/DATOS/stable-diffusion-webui/launch.py", line 128, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DATOS/stable-diffusion-webui/launch.py", line 96, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install rembg requirement for depthmap script.
Command: "/mnt/DATOS/stable-diffusion-webui/venv/bin/python3" -m pip install rembg --prefer-binary
Error code: 1
stdout: <empty>
stderr: ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11; 2.0.32 Requires-Python >3.7, <3.11; 2.0.33 Requires-Python >3.7, <3.11; 2.0.34 Requires-Python >3.7, <3.11; 2.0.35 Requires-Python >3.7, <3.11
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
ERROR: No matching distribution found for rembg

Launching Web UI with arguments: 
No module 'xformers'. Proceeding without it.
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/mnt/DATOS/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/DATOS/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/DATOS/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 58, in <module>
    from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
  File "/mnt/DATOS/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/inpaint/mesh.py", line 16, in <module>
    from moviepy.editor import ImageSequenceClip
ModuleNotFoundError: No module named 'moviepy'

Loading weights [6ce0161689] from /mnt/DATOS/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /mnt/DATOS/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0): 
Model loaded in 2.0s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.7s, apply half(): 0.4s, move model to device: 0.4s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 4.9s (import torch: 0.7s, import gradio: 0.5s, import ldm: 0.3s, other imports: 0.6s, load scripts: 0.5s, load SD checkpoint: 2.1s, create ui: 0.1s).

**Comment by thygate** [comment]
>stderr: ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11

try python 3.10

**Comment by pepebc** [comment]
> > stderr: ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11
> 
> try python 3.10

python 3.10 is OK, thanks
