### ISSUE TITLE
Which folder  to put downloaded ZoeDepth model? 

### ISSUE THREAD

**Issue by LanceGao97** [thygate/stable-diffusion-webui-depthmap-script#229]
I  tested the workflow,   and res101 is working good,   
all those midas model does a bad work,

and I doult if ZoeDepth can do better job, 
 but it's errored  cause I don't have any folder with Zoe Models,
I downloaded ZoeModels  here,   all 3 of them, bu Idon''t know  where to put them.
https://github.com/isl-org/ZoeDepth/releases/tag/v1.0

Which folder  to put downloaded ZoeDepth model?

**Comment by brianjorden** [comment]
Just took at mine and they ended up here:

`stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/checkpoints/`

Although, I thought I remembered that model just downloaded itself when first going to use it, but it has been a while, not sure. As for the quality of ZoeDepth vs res101, I personally find the Zoe ones way better, but specifically the "indoor" one is even better to me than the more generic NK default one of theirs if actually working with indoor scenes.

**Comment by LanceGao97** [comment]
> This has been answered before, all models are download by the extension directly into /models/ except for the zoedepth models which are downloaded through torch hub.
> 
> They can be found here : ~/.cache/torch/hub/checkpoints/

THanks,   my internet use proxy,  I download each model by hand copy links from CMD window, and restart.

**Comment by LanceGao97** [comment]
> Just took at mine and they ended up here:
> 
> `stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/checkpoints/`


Thanks , I copied those 3 brothers there, hope they workss.
