### ISSUE TITLE
cant download latest_net_G.pth

### ISSUE THREAD

**Issue by Lalimec** [thygate/stable-diffusion-webui-depthmap-script#256]
https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth is unresponsive most of the times, i get timeouts. i ve used this in case anyone needs it https://huggingface.co/lllyasviel/Annotators/blob/main/latest_net_G.pth

**Comment by sbersier** [comment]
Same for me. Thanks to @Lilimec

**Comment by semjon00** [comment]
Now it is more reliable - the huggingface mirror will be prioritized. @Lalimec Thank you for suggestion

**Comment by thygate** [comment]
Thanks @Lalimec  and @semjon00 !
