### ISSUE TITLE
cant load script

### ISSUE THREAD

**Issue by nv0001** [thygate/stable-diffusion-webui-depthmap-script#27]
venv "E:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI

loading Dreambooth reqs from E:\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.

Launching Web UI with arguments:
Error loading script: depthmap.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "E:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "E:\stable-diffusion-webui\scripts\depthmap.py", line 72
    <title>stable-diffusion-webui-depthmap-script/depthmap.py at main · thygate/stable-diffusion-webui-depthmap-script · GitHub</title>
                                                                      ^
SyntaxError: invalid character '·' (U+00B7)

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [19810fe6] from E:\stable-diffusion-webui\models\Stable-diffusion\berry_mix.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

Midas and script in proper places

**Comment by thygate** [comment]
><title>stable-diffusion-webui-depthmap-script/depthmap.py at main ...
Looks like you downloaded the depthmap.py script as html.

**Comment by thygate** [comment]
closing this as it is not an issue with the source, but user error..

**Comment by nv0001** [comment]
yep!
thanx and sorry if i posted my troble in wrong place.
Working  now

**Comment by thygate** [comment]
no problem, easy mistake to make. Have fun ! =)
