### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yandw** [thygate/stable-diffusion-webui-depthmap-script#271]
[stable-diffusion-webui-depthmap-script](https://github.com/thygate/stable-diffusion-webui-depthmap-script/tree/main)/[scripts](https://github.com/thygate/stable-diffusion-webui-depthmap-script/tree/main/scripts)
/depthmap.py

![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/6669169/3ff20a87-9133-45f5-aa13-f27a4e7777c1)

Bug？

**Comment by semjon00** [comment]
No, it is downloading model from "../model/edge-model.pth" (from the internet) to "../edge_model.pth" (to the computer). Simply a small inconsistency.

**Comment by semjon00** [comment]
Meh, it works and does not contribute to the tech debt - absolutely ok as-is in my opinion.
