### ISSUE TITLE
couldn't lunch it the error is below 

### ISSUE THREAD

**Issue by Rannmy** [thygate/stable-diffusion-webui-depthmap-script#274]
*** Error running install.py for extension E:\Programs\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script.
*** Command: "E:\Programs\sd-webui-aki-v4\py310\python.exe" "E:\Programs\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\install.py"
*** Error code: 1
*** stdout: Installing transforms3d>=0.4.1 requirement for depthmap script
*** 
*** stderr: Traceback (most recent call last):
***   File "E:\Programs\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\install.py", line 37, in <module>
***     ensure('transforms3d', '0.4.1')
***   File "E:\Programs\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\install.py", line 21, in ensure
***     launch.run_pip(cmd, msg)
***   File "E:\Programs\sd-webui-aki-v4\modules\launch_utils.py", line 130, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "E:\Programs\sd-webui-aki-v4\modules\launch_utils.py", line 107, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install transforms3d>=0.4.1 requirement for depthmap script.
*** Command: "E:\Programs\sd-webui-aki-v4\py310\python.exe" -m pip install "transforms3d>=0.4.1" --prefer-binary --index-url https://mirror.baidu.com/pypi/simple
*** Error code: 1
*** stdout: Looking in indexes: https://mirror.baidu.com/pypi/simple, https://mirrors.aliyun.com/pypi/simple
*** Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
*** Collecting transforms3d>=0.4.1
***   Using cached https://mirrors.aliyun.com/pypi/packages/bd/65/915840e94f946e878f3081da6f42c313162d23118bc2e81d7206600eaf00/transforms3d-0.4.1.tar.gz (1.4 MB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'error'
*** 
*** stderr:   error: subprocess-exited-with-error
***   
***   × python setup.py egg_info did not run successfully.
***   │ exit code: 1
***   ╰─> [6 lines of output]
***       Traceback (most recent call last):
***         File "<string>", line 2, in <module>
***         File "<pip-setuptools-caller>", line 34, in <module>
***         File "C:\Users\Ran\AppData\Local\Temp\pip-install-nth7l4hr\transforms3d_f402f00f598246019b2bb79649d16016\setup.py", line 8, in <module>
***           import versioneer
***       ModuleNotFoundError: No module named 'versioneer'
***       [end of output]
***   
***   note: This error originates from a subprocess, and is likely not a problem with pip.
*** error: metadata-generation-failed
*** 
*** × Encountered error while generating package metadata.
*** ╰─> See above for output.
*** 
*** note: This is an issue with the package mentioned above, not pip.
*** hint: See above for details.
***

**Comment by Rannmy** [comment]
*** Error loading script: depthmap.py
    Traceback (most recent call last):
      File "E:\Programs\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Programs\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Programs\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 70, in <module>
        from inpaint.mesh import write_mesh, read_mesh, output_3d_photo
      File "E:\Programs\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\inpaint\mesh.py", line 25, in <module>
        from inpaint.mesh_tools import get_depth_from_maps, get_map_from_ccs, get_edge_from_nodes, get_depth_from_nodes, get_rgb_from_nodes, crop_maps_by_size, convert2tensor, recursive_add_edge, update_info, filter_edge, relabel_node, depth_inpainting
      File "E:\Programs\sd-webui-aki-v4\extensions\stable-diffusion-webui-depthmap-script\inpaint\mesh_tools.py", line 33, in <module>
        import transforms3d
    ModuleNotFoundError: No module named 'transforms3d'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by semjon00** [comment]
Apparently the venv environment on your PC is broken - versioneer module must be installed for `numpy` to work. Please delete `venv` folder and try again - this would be the easiest solution.

**Comment by semjon00** [comment]
@Rannmy feel free to open a new issue if the advice above did not help
