### ISSUE TITLE
Error-Code during Video-Generation - But Output is ok

### ISSUE THREAD

**Issue by Five-Birds** [thygate/stable-diffusion-webui-depthmap-script#277]
I have the following issue when generating videos:

WARNING: Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
WARNING:vispy:Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.

The output video looks good, so i just want to understand what this error means and if it is effecting the results.

BR Five-Birds

**Comment by thygate** [comment]
safe to ignore this warning

**Comment by Five-Birds** [comment]
Thanks!
