### ISSUE TITLE
When generating I get "Download failed"

### ISSUE THREAD

**Issue by vigfuz** [thygate/stable-diffusion-webui-depthmap-script#281]
When generating I get the following in my terminal:

DepthMap v0.3.12 (54193c4f)
device: cpu
Loading model weights from  ./models/leres/res101.pth
Downloading https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download to ./models/leres/res101.pth
Downloading https://huggingface.co/lllyasviel/Annotators/resolve/5bc80eec2b4fddbb/res101.pth to ./models/leres/res101.pth
Download failed. Try again later or manually download the file to that location.
All done.

I have tried to generate using different models and they all give me the same result except zoedepth that give me:
It looks like there is no internet connection and the repo could not be found in the cache

Any suggestions on how to fix this?

Setup:
- Macbook pro
- 2,4GHz Quad-Core Intel Core i5
- Intel iris plus graphics 655 1536 mb
- 16GB ram 2133MHz
- Mac OS Ventura 13.4.1

Stabel diffusion
version: v1.4.1
Python: 3.10.7
Torch: 2.0.1
Xformers: N/A
Gradio: 3.32.0

**Comment by vigfuz** [comment]
Alright and thanks for the reply.

It could be that my mesh network that is doing something to the connection.
I installed the files manually for the res101 and it is working fine.

On a sidenote, is there any documentation anywhere on the different models?
Is there any of them that are better than another?

**Comment by thygate** [comment]
see the readme and the linked repositories for more info on the models. Newest and best models are zoedepth.

**Comment by vigfuz** [comment]
Great, thanks!
