### ISSUE TITLE
[Feature request] API

### ISSUE THREAD

**Issue by semjon00** [thygate/stable-diffusion-webui-depthmap-script#282]
Thanks @graemeniedermayer for suggestion.

Example: https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/api.py

**Comment by graemeniedermayer** [comment]
I've started working on a branch for this here. https://github.com/graemeniedermayer/stable-diffusion-webui-normalmap-script/tree/depth_api .

There's still some pretty big bugs and hacky stuff. In particular if @semjon00 or @thygate  know a good method for loading either default values or the user values for the depthmap that would be very helpful. 

right now I'm using, 

```
faux_input = on_ui_tabs(True) 
faux_input_list = faux_input.enkey_body()
faux_input_list = [faux.value for faux in faux_input_list]
faux_input_list.append(faux_input.enkey_tail().value)
```

to get the parameters to run `run_generate(*faux_input_list, **override)` which just is very non-ideal. Although this would be robust against ui changes. Mainly the edits to `on_ui_tabs` is something I don't feel comfortable with.

**Comment by semjon00** [comment]
@graemeniedermayer This is great news! Please target `standalone-interface` branch for now, it will be easier to merge it later. By the way, have you had a chance to check out the normalmap generation (in the `dev` branch) I took from your repository?

**Comment by graemeniedermayer** [comment]
My most recent update is pretty independent from the main script although some of the imports might need to change. 

`By the way, have you had a chance to check out the normalmap generation (in the dev branch) I took from your repository?`

Mostly looks great! One thing I'm not so sure about is the final normalisation step, because normals are vectors

```
normal = (normal - normal.min()) / (normal.max() - normal.min())  # normalize to [0; 1]
normal = np.clip(normal * 256, 0, 256 - 0.1)  # Clipping form above is needed to avoid overflowing
normal = normal.astype(np.uint8)
```

Any example of where this might fail if you have an normal image with all vectors of (sqrt(2), sqrt(2), 0) that will become output (1, 1, 0) which no longer has unitary vectors. So I think you'd want to do a vector-wise normalisation. 

So something like

```
n = np.linalg.norm(normal, axis=2)
normal[:, :, 0] /= n
normal[:, :, 1] /= n
normal[:, :, 2] /= n
normal += 1
normal /= 2
normal = np.clip(normal * 256, 0, 256 - 0.1)   # Clipping form above is needed to avoid overflowing
normal = normal.astype(np.uint8)
```

I am also not a huge fan of the post blur so maybe we should remove it.

**Comment by semjon00** [comment]
@graemeniedermayer Right, should normalize individual vectors/pixels 😅
As for post-blur, my math intuition says that this is not a terribly bad idea - but maybe I am wrong.
Force-pushed a new version, could you please give it a look?

**Comment by semjon00** [comment]
@graemeniedermayer Aside from that, is it ok to push?

**Comment by graemeniedermayer** [comment]
Yup it's looking good! 

Also with the single video there are 16 bit formats. Mostly FFV1 codec with either avi or nut as a video container (avi is a much more supported format). 16bit isn't super well supported by most video editors (blender might be able to understand 16bit avi I'll have to experiment).

https://stackoverflow.com/questions/62815543/python-16bit-grayscale-video-from-series-of-images

**Comment by graemeniedermayer** [comment]
Oh also should this issue be closed? because of https://github.com/thygate/stable-diffusion-webui-depthmap-script/pull/296

**Comment by semjon00** [comment]
@graemeniedermayer Right, closed the issue :)
Just pushed normalmap generation into the main: 74dc96bab2dbb058652e03a373a8fe3d10bb661d. Now the job of migrating users to this repository is almost completed (https://github.com/thygate/stable-diffusion-webui-depthmap-script/discussions/272). Once they hop into this repo, they will get some extra goods (like generating normalmaps with zoedepth). This could be accelerated a bit. @graemeniedermayer Could you please change the [NormalMap repository](https://github.com/graemeniedermayer/stable-diffusion-webui-normalmap-script/tree/main) so it redirects users to this repository? Otherwise they might not find out that this repo allows generating normalmaps, too. Archiving would also help.

**Comment by semjon00** [comment]
🙂
If this is installed as a WebUI script, then all the needed dependencies will be installed on the first WebUI run, into the corresponding venv.

**Comment by G-force78** [comment]
> 🙂 If this is installed as a WebUI script, then all the needed dependencies will be installed on the first WebUI run, into the corresponding venv.

No I use it as a standalone app as google block it on free tier. I think i sorted it anyway thanks.
