### ISSUE TITLE
[Feature request] output stereo3d image into separate left and right file

### ISSUE THREAD

**Issue by T0biasCZe** [thygate/stable-diffusion-webui-depthmap-script#285]
Hi, would it be possible to add _(another)_ output option for outputting the stereo 3d image as two left right files? eg image_left.png and image_right.png instead of combined side by side?

**Comment by semjon00** [comment]
@T0biasCZe There have been some other things in the shortlog, but now this option is available in the `next` branch (soon they will become available in the `main` branch).
