### ISSUE TITLE
The Depth tab doesnt appear

### ISSUE THREAD

**Issue by frederikulnitsvester** [thygate/stable-diffusion-webui-depthmap-script#289]
Opposite to the tutorials, the "depth" tab doesn't show after installation, updating and restarting. Does anyone know what the problem could be? Thanks!

**Comment by frederikulnitsvester** [comment]
https://cdn.discordapp.com/attachments/1002602742667280404/1130878388878459010/CleanShot_2023-07-18_at_17.06.252x.png

I get this error in the LOGs. I have a Macbook M2, 16gb ram. Is there a way to get it to work without an Nvidia graphic card?

**Comment by semjon00** [comment]
@frederikulnitsvester
