### ISSUE TITLE
it took a very very long time to bach depthmap with zoedepth_n module

### ISSUE THREAD

**Issue by jasoncow007** [thygate/stable-diffusion-webui-depthmap-script#292]
it is much more faster when use res101, but the result isn't that good,,,,,
during the processing,  there's no button to interupt it,,,,,
what's the matter with zoedepth processing coz the long time waiting,,

**Comment by jasoncow007** [comment]
it may caused by big resolution map need combine 512,,,,but gpu works in low percentage of TDP and very slow,  dont know why

**Comment by semjon00** [comment]
Please share the details about your system - GPU, CPU, amount of RAM. Are you sure you are generating using GPU? There is a GPU option in the UI. BOOST takes a very long time, please do not use it if it is an issue.

**Comment by jasoncow007** [comment]
ur,,, im not complainning, i'm trying to check confirm wiht u if it's a problem,my  gpu 3070 16g vram and working on 39% TDP when computing depthmap,  core 100% and mem  97.8%

**Comment by semjon00** [comment]
I think core 100% means that it works correctly. However, mem 97.8% is not ok. Maybe some other extensions eat all the memory, or you are using BOOST. If you want to make the process faster, use a smaller model (midas_v21_small is the smallest) - it is faster, but the quality is worse. Batch processing is faster than processing multiple images separately. (And BOOST, well, is extra slow - maybe do not use, at least with zoedepth.)
