### ISSUE TITLE
Left and right edges of stereo image not inpainted

### ISSUE THREAD

**Issue by tommaier123** [thygate/stable-diffusion-webui-depthmap-script#294]
When generating a stereo image there are a few pixels ot the right and left that are not really inpainted. It looks like the last proper pixel is just duplicaetd until the edge.

![stereo_crop](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/40432491/82ccac48-7c3a-4e73-9927-3763c8901f61)

![stereo](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/40432491/f5e8a55f-3975-4666-b96e-8870b6f900af)

**Comment by semjon00** [comment]
Correct! There is no information to fill these areas, so it is simply stretched. Currently (v0.4.0) the stereo generation is not very smart (compared with how smart it could be), there is no infilling/inpainting. You may try adjusting the separation - this moves images closer together or more apart.

**Comment by tommaier123** [comment]
Maybe as an easy workaround a option that just cuts off a bit of the left and right for both stereo images could work.

**Comment by semjon00** [comment]
Was my idea, too, but this would make stereoimage not be exactly two times as large as the input image. Plus, cuts from two different sizes could be different sizes, so the center of the stereoimage would not split right and left parts in half... And a new option would clutter stereoimage generation interface even more...

If you could create a good MR where there is a hidden option (see `src.depthmap.on_ui_settings`) to enable this option in the UI, then I would be happy to review and merge it 😀
