### ISSUE TITLE
Normal maps and Python 3.8

### ISSUE THREAD

**Issue by graemeniedermayer** [thygate/stable-diffusion-webui-depthmap-script#299]
I think this type hinting feature was introduced in python 3.10 so maybe we shouldn't use it for compatible reasons.

I got this error with python 3.8
```
pre_blur: int | None = None, sobel_gradient: int | None = 3, post_blur: int | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by graemeniedermayer** [comment]
also I think pre-scaling the depth down seems to give less harsh normal maps

with normalmap = normalmap/256 near start
![depthmap-0332normalmap](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/38518120/03ca038a-e01a-4012-b6b2-dab1c9315c2f)

without prescaling
![depthmap-0325normalmap](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/38518120/0df93d3c-36ac-4f56-8178-327e6b18a879)

Does zoedepth have a clear conversion rate from depth space to real/metric space?

**Comment by graemeniedermayer** [comment]
Oh I also think at some point the default normals got inverted.

They work with controlnet! I think they are an improvement on the current preprocessors 
![normal_comparison](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/38518120/16745b88-3017-4691-bac4-d9b4726671b0)

**Comment by semjon00** [comment]
> I think this type hinting feature was introduced in python 3.10 so maybe we shouldn't use it for compatible reasons.
> 
> I got this error with python 3.8
> 
> ```
> pre_blur: int | None = None, sobel_gradient: int | None = 3, post_blur: int | None = None,
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
> ```

Sorry, forgot about this again😅

**Comment by semjon00** [comment]
For scaling down: weird why it is so exxagerated despite the normalization... But the result indeed looks better. By the way, I want to re-think how normalisation is always happening with depthmaps and only then they are used for generating other stuff.

**Comment by graemeniedermayer** [comment]
This is before the gradient is taken, so this is still the depthmap.

Thanks! this made me think, It might need to be scaled by the size of the image. Because dx, dy are essentially 1/width, 1/height. So maybe there's a more appropriate multiplier.

`I want to re-think how normalisation is always happening with depthmaps `

Sounds good! Be mindful of types.
