### ISSUE TITLE
this could be an extension instead of custom script

### ISSUE THREAD

**Issue by AUTOMATIC1111** [thygate/stable-diffusion-webui-depthmap-script#30]
I don't know your rationale for making this just a custom script, but in case you didn't know, there is a more convenient way for users to have new functionality added:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions

With this you can install the needed packages automatically and we could add your extension to the wiki which would let users install and use it right from UI.

**Comment by thygate** [comment]
The rationale was that at the time i started the script, extensions were very new, and not much examples or docs were available, but this is now no longer the case.

I know about the extensions, and always planned to convert the script to one, but did not get around to it yet ..
Recently being able to solve the memory leak/fragmentation issue has given me the confidence to move on to converting to an extension, I hope to find more time this week to work on it.  

Thanks for commenting, I appreciate it, and I will get to converting to an extension.

**Comment by cluder** [comment]
i think you simply have to move the .py script to a scripts directory, and its installable as an extension: scripts/depthmap.py, nothing else.
The midas repo  was already there in my case, not sure if it comes now with automatic1111 by default, or if another extension already created it.

**Comment by thygate** [comment]
Done. I wanted to have some time to properly test everything, which I did, I did not realize it would be this simple.
