### ISSUE TITLE
Two depth maps output?

### ISSUE THREAD

**Issue by sammy3d** [thygate/stable-diffusion-webui-depthmap-script#322]
Looks like the newest version is producing two identical depth maps. Is the second one necessary?

**Comment by sammy3d** [comment]
Investigating further....one is a jpeg and the other a png file. Both are duplicates.

**Comment by semjon00** [comment]
There is a setting in WebUI that automatically creates downscaled and compressed jpg-s from every png that is saved. Sometimes this is a useful feature, but not in this case. It can be disabled thankfully.
