### ISSUE TITLE
Add generation settings metadata to file

### ISSUE THREAD

**Issue by davisburnside** [thygate/stable-diffusion-webui-depthmap-script#331]
It would be nice if the image output could add the model used, background clip depth, etc.

**Comment by semjon00** [comment]
I totally agree, it would be nice if someone could add this feature. Sadly, I won't have time to get to this anytime soon, I am busy with other things right now.

**Comment by semjon00** [comment]
Duplicate of https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/280
