### ISSUE TITLE
Stereo Image generation is broken since Automatic1111 1.6.0 using text2image and loading it as script 

### ISSUE THREAD

**Issue by LVNSDCAPE** [thygate/stable-diffusion-webui-depthmap-script#333]
If i launch SD 1.6.0 i do now receive right from the start 

WARNING:py.warnings:L:\SD_1.60\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\common_ui.py:263: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):

WARNING:py.warnings:L:\SD_1.60\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\common_ui.py:301: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  result_images = gr.Gallery(label='Output', show_label=False,

WARNING:py.warnings:L:\SD_1.60\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\common_ui.py:301: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  result_images = gr.Gallery(label='Output', show_label=False,

In Text2image i do activate the depth script and set up everything for generating stereo side by side content 

Model: RES
Everything else default 
  
I do click generate, it generates the normal picture then starts to convert the 3D Stereo 

It first seems to work then errors with 

** Error completing request████████████████████████████████████████████████████████████| 20/20 [00:17<00:00, 10.77it/s]

...

    Traceback (most recent call last):
      File "L:\SD_1.60\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "L:\SD_1.60\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "L:\SD_1.60\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "L:\SD_1.60\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "L:\SD_1.60\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 56, in run
        info = create_infotext(
      File "L:\SD_1.60\stable-diffusion-webui\modules\processing.py", line 694, in create_infotext
        "Tiling": "True" if p.tiling else None,

    AttributeError: 'Processed' object has no attribute 'tiling'

---

If i do convert from the Depth TAB in Automatic1111 with already generated picture content it works without any issues like batch converts.

My Settings 

<a href="https://ibb.co/TMgPsjm"><img src="https://i.ibb.co/whzpfGM/378546782537252.jpg" alt="378546782537252" border="0"></a>

If i revert to Automatic1111 1.5.2 i do not have any Issues with App loading ( errors ) and no issues  in generating stereo images in text2image.

**Comment by semjon00** [comment]
Thanks for reposting! I will take a look at this in the upcoming week.

**Comment by aleqniko** [comment]
Сonfirm. generation of stereo images fails

**Comment by semjon00** [comment]
Please upgrade and try again - do the new update fix the issue?

**Comment by LVNSDCAPE** [comment]
Hi , it is working good now.
No more related errors during launch and processing.
All fine.

Thx a lot for the quick fix  :)
