### ISSUE TITLE
Zoe Models fail to load

### ISSUE THREAD

**Issue by FoxTrotte** [thygate/stable-diffusion-webui-depthmap-script#334]
Hey everyone, I finally managed to get the UI to launch.

Using any model works brilliantly, but using any Zoe models gives this error:

> `Using pretrained resource url::https://github.com/isl-org/ZoeDepth/releases/download/v1.0/ZoeD_M12_N.pt
> Fail.
> 
> Traceback (most recent call last):
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\common_ui.py", line 526, in run_generate
>     input_i, type, result = next(gen_obj)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\core.py", line 326, in core_generation_funnel
>     raise e
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\core.py", line 127, in core_generation_funnel
>     model_holder.ensure_models(inp[go.MODEL_TYPE], device, inp[go.BOOST])
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\depthmap_generation.py", line 67, in ensure_models
>     self.load_models(model_type, device, boost)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\src\depthmap_generation.py", line 185, in load_models
>     model = build_model(conf)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dzoedepth\models\builder.py", line 51, in build_model
>     return get_version(config.version_name).build_from_config(config)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dzoedepth\models\zoedepth\zoedepth_v1.py", line 250, in build_from_config
>     return ZoeDepth.build(**config)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dzoedepth\models\zoedepth\zoedepth_v1.py", line 245, in build
>     model = load_state_from_resource(model, pretrained_resource)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dzoedepth\models\model_io.py", line 84, in load_state_from_resource
>     return load_state_dict_from_url(model, url, progress=True)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dzoedepth\models\model_io.py", line 61, in load_state_dict_from_url
>     return load_state_dict(model, state_dict)
>   File "F:\Dossiers\Stable-Diffusion-Depth-Standalone\dzoedepth\models\model_io.py", line 49, in load_state_dict
>     model.load_state_dict(state)
>   File "C:\Users\natha\anaconda3\envs\depth\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for ZoeDepth:
>         Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index".`

I don't really know what's happening here, can anyone help out ?
Thanks !!!
(Using W10, Python 3.10 in anaconda environment. torch 2.0.2 and cu118)

**Comment by graemeniedermayer** [comment]
It looks like it might be a failure to download or corruption of ZoeD_M12_N.pt or some config file. What is the size of ZoeD_M12_N.pt ?

**Comment by sammy3d** [comment]
It seems this error only popped up for me after I updated to DepthMap v0.4.4 (4c55ebd7)?

**Comment by semjon00** [comment]
@sammy3d @FoxTrotte could you please go to the _Settings tab -> Sysinfo -> Download system info_ and post the downloaded file here?

**Comment by sammy3d** [comment]
I see a system section under settings but no option to download system info?

**Comment by semjon00** [comment]
Please find a way to download the information about the system. Please make sure that you use SD WebUI version 1.6.0

**Comment by appsmalthouse** [comment]
I too was having this issue: 

`Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\common_ui.py", line 526, in run_generate
    input_i, type, result = next(gen_obj)
  File "E:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 326, in core_generation_funnel
    raise e
  File "E:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\src\core.py", line 127, in core_generation_funnel
    model_holder.ensure_models(inp[go.MODEL_TYPE], device, inp[go.BOOST])
...

RuntimeError: Error(s) in loading state_dict for DPTDepthModel:
        Unexpected key(s) in state_dict: "pretrained.model.blocks.0.attn.relative_position_index",`

The solution for me was to update to web-ui 1.6.0 was on 1.5.1 

it now works for me.

**Comment by sammy3d** [comment]
updating to web-ui 1.6 seems to have fixed the error. I also see the sysinfo section on the settings tab now.

**Comment by Apacchi88** [comment]
I still get the error: Using pretrained resource url::https://github.com/isl-org/ZoeDepth/releases/download/v1.0/ZoeD_M12_N.pt
Fail.
[sysinfo-2023-09-09-11-04.txt](https://github.com/thygate/stable-diffusion-webui-depthmap-script/files/12565596/sysinfo-2023-09-09-11-04.txt)

**Comment by graemeniedermayer** [comment]
> I still get the error: Using pretrained resource url::https://github.com/isl-org/ZoeDepth/releases/download/v1.0/ZoeD_M12_N.pt Fail. [sysinfo-2023-09-09-11-04.txt](https://github.com/thygate/stable-diffusion-webui-depthmap-script/files/12565596/sysinfo-2023-09-09-11-04.txt)

The only standout I can see if your using timm==0.9.7 and the requirement is timm==0.9.2 . Maybe checking if downgrading the package helps?

**Comment by semjon00** [comment]
@graemeniedermayer Hello! I would be really thankfull if you could find the issue and a create MR with a fix. I can not reproduce this 😒

Sorry for taking too long with the API MR.

**Comment by nagadomi** [comment]
This seems to be yet another compatibility issue that occurs in timm 0.9.6 and later.
I have checked with ZoeDepth's evaluation script. It works up to 0.9.5 with the drop_path patch, but with 0.9.6 I get this error.
Maybe other scripts reinstall 0.9.6 or later.

**Comment by semjon00** [comment]
Hopefully fixed. Please upgrade and test. @nagadomi @graemeniedermayer

**Comment by nagadomi** [comment]
See my fix for reference.
https://github.com/nagadomi/ZoeDepth_iw3/commit/cc9d0bb0b83a6af2437cf84c440873fe235f8ce3
