### ISSUE TITLE
Crashing when doing video

### ISSUE THREAD

**Issue by lividhen** [thygate/stable-diffusion-webui-depthmap-script#337]
Using the fork of webui that supports amd [https://github.com/lshqqytiger/stable-diffusion-webui-directml](here). Generating a single image depth map both in the depth tab and with text to image works fine, but it uses my cpu even when gpu is selected. Text to image uses my gpu as intended, but it switches to cpu when generating the depth map. This seems to make sense as it looks like its exclusively looking for a cuda device. My main issue here is with trying to process a video. When hitting generate the console just gets stuck here: 
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/42221797/c4d27e4b-88cf-49f5-971c-4ea6e1c488a6)
If I leave it there my pc crashes with a bsod. The screen is too distorted to read the error on it.

Here are my settings:
![image](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/42221797/38d81e53-395b-4baa-a73f-254a9f31b9fb)

**Comment by graemeniedermayer** [comment]
You may want to try it without the boost option. Boost+Zoedepth can be massive amount of memory on high resolution videos. I'm not sure how https://github.com/lshqqytiger/stable-diffusion-webui-directml deals with vram but maybe it just hangs rather than crashes?
