### ISSUE TITLE
Is there any way to name generations with a format (model used, gap fill technique) when created from the Depth tab?

### ISSUE THREAD

**Issue by yasavvym8** [thygate/stable-diffusion-webui-depthmap-script#343]
I don't quite seem to be finding it if it exists. I'm sure there's some way to, but I'm not skilled enough to edit whatever settings necessary on my own.

**Comment by semjon00** [comment]
Sadly, it is not possible to change as of now. https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/280

**Comment by yasavvym8** [comment]
That makes sense. Perhaps in the future. Many thanks for the prompt response!
