### ISSUE TITLE
During file naming, seed number not incremented with batch count

### ISSUE THREAD

**Issue by graemeniedermayer** [thygate/stable-diffusion-webui-depthmap-script#35]
**Actual behaviour**
For instance with the prompt building, with a batch count of 2, you'll get output names like:
00675-1600648804-building.png
00676-1600648805-building.png

00677-1600648804-building_depth.png
00678-1600648804-building_depth.png

**Expected behaviour**
So the 1600648804 in the second depth image name should be incremented by 1. This can be a bit a frustration when creating similar depth maps because the numbering is the same. This also makes it so the depth image won't give the correct information to png_info.

**Some of the observations I've made**
`processed.seed` that is used during saving seems to be only the initial seed. There should have some sort of `n_iter` or batch count index added to it. It would be nice to do something like `processed.seed + processed.n_iter` ; however, `n_iter` isn't attached to `processed`. 

**Possible solution**
 Changing `processed.seed` to `processed.all_seeds[count-1]` does seem to work. I haven't tested it for every situation.

**Comment by thygate** [comment]
Yes, that's defenately a bug, thanks for catching this !

`p.n_iter` is available, but the `processed.all_seeds[count-1]` seems like the correct solution, -1 to compensate for the initial grid image..

Or would `processed.seed + p.n_iter` be better ?
