### ISSUE TITLE
'dpt_hybrid' throws error

### ISSUE THREAD

**Issue by maniakid** [thygate/stable-diffusion-webui-depthmap-script#36]
Hi.

I have this error when using 'dpt_hybrid' model on 'GPU':

"view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead."

other models are ok and CPU is fine.

**Comment by thygate** [comment]
That's weird ... could you try deleting the model and let it re-download it ..

**Comment by thygate** [comment]
So the hybrid model does work on cpu ? What commandline arguments are you running with, and what GPU do you have ?

**Comment by maniakid** [comment]
Yes, the hybrid model does work on cpu.

My webui start command is:
`python "webui.py" --autolaunch --allow-code --theme=dark --xformers --force-enable-xformers --opt-split-attention --disable-safe-unpickle --api --port 16666 --cors-allow-origins=https://www.painthua.com`

My GPU is nvidia RTX 2070 8G

**Comment by thygate** [comment]
Try adding `--no-half` to commandline arguments

**Comment by maniakid** [comment]
Hi.

I added the argument and restarted, but still there.

Maybe some of my package versions in my conda enviroment? Just a guess.

**Comment by thygate** [comment]
Can you post the complete message with the stack trace so i can tell where it's coming from ..

**Comment by thygate** [comment]
Do you still have problems with the current version of the extension ?

**Comment by maniakid** [comment]
Yes, problem is gone, everything is ok now and the result is good, awesome!! Thanks~
