### ISSUE TITLE
Memory release issue

### ISSUE THREAD

**Issue by iterhating** [thygate/stable-diffusion-webui-depthmap-script#37]
Possibly a memory leaking issue, as a similar effect is seen here [in this post for depth2mask](https://github.com/Extraltodeus/depthmap2mask/issues/16)

After a run using depthmap2mask the memory allocated during the run is not released, this is clearly visible in a resource monitor looking at the VRAM usage, and reproducible across two machines and several different attempts. Command line flags include --medvram, --full precision, and --no-halfs

**Comment by thygate** [comment]
This issue was fixed for me and other users in v0.1.9 after doing explicit system and torch garbage collection and deleting the model.

For me there is no issue, can you verify this is still the case with the current version of THIS script, that fork might be behind.

**Comment by iterhating** [comment]
I hadn't noticed there was already an update, thanks for the dev tempo. I updated to 0.2.1 (which is all that the extensions tab would update, it won't grab 0.2.2) 

Now, subsequent runs after using depthmap don't trigger OOM errors, and that's pretty much all that matters. However, after the run, the GPU still has about an extra gig of VRAM reserved compared to a normal run. Not sure why, or if it matters.

**Comment by thygate** [comment]
Try deleting the extension folder and re-install the extension from the `Available` subtab under the `Extensions` tab. A lot has changed in the current version.

**Comment by thygate** [comment]
assuming everything is working now, please open a new issue if problems persist.
