### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by calad0i** [thygate/stable-diffusion-webui-depthmap-script#38]
At [L23](https://github.com/thygate/stable-diffusion-webui-depthmap-script/blob/ee06f979a43708e7cb11ac2ff37c9260f4b204ff/scripts/depthmap.py#L23) of the script, the path format separator "\\" assumes the user is using Windows (which should also be escaped). The "/" separator works in both Windows and Linux (also Mac), which should probably be preferred.

**Comment by thygate** [comment]
That's a bug alright, I forgot to edit that path. Fixed now, thanks for catching this.
