### ISSUE TITLE
Marigold branch small fix

### ISSUE THREAD

**Issue by graemeniedermayer** [thygate/stable-diffusion-webui-depthmap-script#388]
I was finding somewhere the ensemble_size was being converted into a float which caused a crash
```
duplicated_rgb = torch.stack([rgb_norm] * ensemble_size)
TypeError: can't multiply sequence by non-int of type 'float' 
```
----
### Potential solution

```
        pipe_out = model(img, processing_res=w, show_progress_bar=False,
                         ensemble_size=marigold_ensembles, denoising_steps=marigold_steps,
                         match_input_res=False)
```
I solved this by casting the variables to int
```
        pipe_out = model(img, processing_res=w, show_progress_bar=False,
                         ensemble_size=int(marigold_ensembles), denoising_steps=int(marigold_steps),
                         match_input_res=False)
```
There might be a better location for ensuring the variables are integers.

**Comment by semjon00** [comment]
Wow, that's weird. Thank you for finding this issue.

Nope, that's not a good solution. Here it's necessary to track down what code causes this unreasonable behavior and how to fix its root cause.

**Comment by graemeniedermayer** [comment]
The conversion may be from the depthmap settings? Because you can input floats into the depth settings there should at least be a check (I haven't changed the default 5).

---
Another strange non-breaking issue I was getting when running on half. It was running on my gpu.
```
Pipelines loaded with `torch_dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
```

`model.from_pretrained` may need an `device_map` argument although you'd need to rework some other things.

**Comment by semjon00** [comment]
Sorry, I will be unavailable for a week. I would heavily appreciate if you would propose specific changes to fix that behavior. I will certainly have time to get these into the branch. Please note that the bundled Marigold is outdates, the authors are fast in developing it. First they removed xformers as hard dependency, then added f16 mode (independently from me).

**Comment by graemeniedermayer** [comment]
Yes no problem! Sorry I was just making notes. This is an incredible busy time of year. I'll put together a pull later today so at least it'll be more specific.

This is low priority because it's likely some of these problems will resolve themselves with marigold updates (updated 3 hours ago).
