### ISSUE TITLE
Error using BOOST in V0.2.4 No such file or directory: './models/pix2pix/latest_net_G.pth'

### ISSUE THREAD

**Issue by greyphilosophy** [thygate/stable-diffusion-webui-depthmap-script#39]
I just installed V0.2.4 and did not have any previous depth software on this machine. On the img2img tab, using batch img2img, with the BOOST checkbox selected, after hitting Generate I find the error below in console and the generate fails. I'm guessing that I need to install pix2pix but I'm not really sure.

```
DepthMap v0.2.4
device: cuda
Loading model weights from  ./models/midas/dpt_large-midas-2f21e586.pt
Downloading model weights to ./models/pix2pix/latest_net_G.pth
Error completing request
Arguments: (2, '', '', 'None', 'None', None, None, None, None, None, 0, 1, 0, 4, 0, 1, False, False, 1, 1, 1, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, 'C:\\stable-diffusion-webui\\outputs\\txt2img-images\\travels\\00091', 'C:\\stable-diffusion-webui\\outputs\\txt2img-images\\travels\\00091\\depth2', 11, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False, False, 4.0, '', 10.0, False, True, True, 30.0, True, False, False, 0, 0.0, 10.0, True, 30.0, True, 0, 0, 384, 384, True, False, True, True, True, False, True, 1) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 190, in run
    download_file(pix2pixmodel_path,"https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth")
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 84, in download_file
    with open(filename, 'wb') as fout:
FileNotFoundError: [Errno 2] No such file or directory: './models/pix2pix/latest_net_G.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 146, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, args)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 46, in process_batch
    proc = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 455, in run
    del pix2pixmodel
UnboundLocalError: local variable 'pix2pixmodel' referenced before assignment
```

**Comment by graemeniedermayer** [comment]
This was the same message I got when the model didn't download. I have notice the model download link seems to be a little unreliable. It didn't work for me the first time. I retried a few minutes later and it worked.

 It downloads from https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth . I'm not sure if there's another source for the model. 

This is one of those problems that might resolve by restarting auto1111 and retrying a few times.

**Comment by thygate** [comment]
>Downloading model weights to ./models/pix2pix/latest_net_G.pth
Error completing request

It could not download the model, the server seems to be unreliable, try downloading the file manually and place in /models/pix2pix
https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth

**Comment by greyphilosophy** [comment]
Downloading it and creating the folder for it manually worked, thank you both!

So two thoughts: was/am I missing a pix2pix module? And secondly would it make sense to add a custom error message to suggest this workaround when the latest_net_G.pth file is missing?

**Comment by thygate** [comment]
v0.2.5 now checks the download and exits with a clear message instead of an Exception if it failed. download now also has fancy a progress bar.

**Comment by dogederp** [comment]
> > Downloading model weights to ./models/pix2pix/latest_net_G.pth
> > Error completing request
> 
> It could not download the model, the server seems to be unreliable, try downloading the file manually and place in /models/pix2pix https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth
> 
> edit: it's the only source I'm aware of, and I'm not sure if it would be ok to just mirror it ..

Is there a mirror of the file? I'm trying to download it trough https://sfu.ca/~yagiz/CVPR21/latest_net_G.pth but it takes between 6 to 8 hours for me to download this 304 mb file using this site.

**Comment by thygate** [comment]
I see the sfu.ca server is acting up again, can't connect either..  Glad you were able to download the file eventually ..
There are more new issues about this ..

**Comment by e813519** [comment]
use chinese xunlei soft,can down with 200K/s.

**Comment by LanceGao97** [comment]
> 

paste the link  to your Browser,   it downloads as fast as flying birds,
