### ISSUE TITLE
marigold model load error

### ISSUE THREAD

**Issue by tufeixp** [thygate/stable-diffusion-webui-depthmap-script#396]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/Bingxin/Marigold (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020010184040>, 'Connection to huggingface.co timed out. (connect timeout=None)'))

**Comment by semjon00** [comment]
HuggingFace or your internet were faulty at that time.

**Comment by tufeixp** [comment]
@semjon00 I tried to change the model_path as:
            #model_path = "Bingxin/Marigold"
            model_path = "prs-eth/marigold-depth-v1-0"
where I found ok to visit using web browser for me, but still not work. Any guild to manually download the model files to put to somewhere?
