### ISSUE TITLE
Extension does not add itself to the API of SD.next

### ISSUE THREAD

**Issue by aaronsantiago** [thygate/stable-diffusion-webui-depthmap-script#404]
The method that the extension uses to detect whether its working within an installation of the webui seems to not work with sdnext: https://github.com/thygate/stable-diffusion-webui-depthmap-script/blob/5250c8b7ea895a4b15575d17a278c88c38cb2132/src/backbone.py#L76

This causes it to run in standalone mode and--i assume--skip the part where it adds itself to the API.

The depth endpoint is missing from the docs and 404s when I try to ping it.

Otherwise, the extension works completely within the UI.

**Comment by aaronsantiago** [comment]
Relevant issue in SD.next https://github.com/vladmandic/automatic/issues/2801

**Comment by semjon00** [comment]
Thanks for reporting! I won't have time to fix this :(
I will be happy to merge the fix if somebody would create one.

**Comment by aaronsantiago** [comment]
Support was just added in sd.next dev. Thanks!
