### ISSUE TITLE
ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by martinobettucci** [thygate/stable-diffusion-webui-depthmap-script#41]
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/stable-diffusion-webui/extensions/depthmap-script/scripts/depthmap.py", line 38, in <module>
    from lib.multi_depth_model_woauxi import RelDepthModel
ModuleNotFoundError: No module named 'lib'

Error since "https://github.com/thygate/stable-diffusion-webui-depthmap-script/commit/ee06f979a43708e7cb11ac2ff37c9260f4b204ff"

I've removed and reinstalled the plug-in, checked the midas/BoostingMonocularDepth repositories are in place.

Did the author added some library code without make the install steps?
Which are the install steps?
I can't find any "lib" folder, nor in the webui nor in this repository?

**Comment by martinobettucci** [comment]
Nevermind, it seems the new repos are not loaded after a simple "apply for update". You need to shutdown the webui completely and run it again.

Leaving this for future references.

**Comment by thygate** [comment]
I thought i had that in the readme, that you need to restart, but it got lost in some of the changes it seems, I will add it back.

**Comment by pluieciel** [comment]
Hello, I got the same error.
I dont have "launch", and "pip install launch" not working, since some dependency conflict.
I tried to manually install, I "git clone" the two repositories into the /repositories/midas (manually modified with lowercase)  and  /r../BoostingMonocularDepth
I think the "lib" is inside BoostingMD folder, do I need to manually add something to make it work?

I dont really understand the following command, what is the 3rd argument?
launch.git_clone("https://github.com/isl-org/MiDaS.git", "repositories/midas", "midas")

thanks a lot!

**Comment by thygate** [comment]
the last param for git_clone is the commit hash, just ignore it or leave blank.

You should clone the midas repo to
`/repositories/midas`
and boostinmonoculardepth to
`/repositories/BoostingMonocularDepth`

both case sensitive.

From the /stable-diffusion-webui/ directory, run the following 2 commands :

`git clone https://github.com/isl-org/MiDaS.git repositories/midas`

and 

`git clone https://github.com/compphoto/BoostingMonocularDepth.git repositories/BoostingMonocularDepth`

**Comment by pluieciel** [comment]
Thanks a lot for your help!
The reason is that I run a bash file to start "python .../..env/stable_d_w/webui.py" at my home directory, so python pwd is not the stable_diffusion_webui folder and it cannot find the "lib".
I cd to the folder and then run webui.sh, there is no issue now.

**Comment by JasonHoku** [comment]
Hey I just wanted to mention I had this issue today on Windows and I ended up tracing the error to the midas install, git cloning and renaming the Next_VIT repo and changing lines 8 and 9 to directly point to Next_VIT:

```py
file = open("D:/AUTOMATIC1111stable-diffusion-webui/stable-diffusion-webui/repositories/Next-ViT/classification/nextvit.py", "r")
source_code = file.read().replace(" utils", " .. .. Next_ViT.classification.utils")
```

**Comment by thygate** [comment]
> Hey I just wanted to mention I had this issue today on Windows and I ended up tracing the error to the midas install, git cloning and renaming the Next_VIT repo and changing lines 8 and 9 to directly point to Next_VIT:
> 
> ```python
> file = open("D:/AUTOMATIC1111stable-diffusion-webui/stable-diffusion-webui/repositories/Next-ViT/classification/nextvit.py", "r")
> source_code = file.read().replace(" utils", " .. .. Next_ViT.classification.utils")
> ```

This code does not use or reference anything in /repositories/Next-ViT
