### ISSUE TITLE
NameError: name 'video_mesh_data' is not defined

### ISSUE THREAD

**Issue by KimKyanghyun** [thygate/stable-diffusion-webui-depthmap-script#413]
![KakaoTalk_20240227_202549372](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/132927737/ad0908f7-26e6-49c2-ae42-dd164c998870)

NameError: name 'video_mesh_data' is not defined

This error keeps popping up.
May I know why?

**Comment by semjon00** [comment]
Please upgrade the plugin (the current version is 0.4.6) and try again.
