### ISSUE TITLE
[Question] How to add other weights?

### ISSUE THREAD

**Issue by eyeEmotion** [thygate/stable-diffusion-webui-depthmap-script#415]
Hi,

I want to try 'dpt_swin_large_384' and 'dpt_swin2_large_384' with the depthmap generator. I have put them in "...\stable-diffusion-webui\models\midas", as I have Depthmap installed as an extension. But how do I get them in the dropdown list, to use them?

Also, how can I replace the 'dpt_beit_large_512.pt', as it seems to give errors with me.

PS: those batch jobs are only for images, not videos?

Cheers

**Comment by semjon00** [comment]
Sorry, adding new models automatically is not supported. Yes, batch conversion works for images only
