### ISSUE TITLE
UnboundLocalError: local variable 'grad_resized' referenced before assignment

### ISSUE THREAD

**Issue by patrickmros** [thygate/stable-diffusion-webui-depthmap-script#43]
I tried CPU and GPU, nothing worked. Tried to use an already generated image, set "crop and resize" and "denoising strength" to 0.

Full terminal output:

`DepthMap v0.2.6
device: cpu
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
Error completing request
Arguments: (0, '', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=512x704 at 0x29EC9671C90>, None, None, None, None, 0, 60, 0, 4, 0, 1, False, False, 1, 1, 1, 0, -1.0, -1.0, 0, 0, 0, False, 512, 768, 1, False, 32, 0, '', '', 9, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, 1, 4, 512, 768, False, False, True, True, True, False, True, 1) {}
Traceback (most recent call last):
  File "J:\sd_06_10_2022\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "J:\sd_06_10_2022\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "J:\sd_06_10_2022\stable-diffusion-webui\modules\img2img.py", line 150, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "J:\sd_06_10_2022\stable-diffusion-webui\modules\scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "J:\sd_06_10_2022\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 229, in run
    prediction = estimateboost(img, model, model_type, pix2pixmodel)
  File "J:\sd_06_10_2022\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 917, in estimateboost
    whole_image_optimal_size, patch_scale = calculateprocessingres(img, net_receptive_field_size, r_threshold_value, scale_threshold, whole_size_threshold)
  File "J:\sd_06_10_2022\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 517, in calculateprocessingres
    grad_region = cv2.dilate(grad_resized, kernel2, iterations=1)
UnboundLocalError: local variable 'grad_resized' referenced before assignment`

**Comment by thygate** [comment]
Please try without boost first. Do any of the midas models (first four models in the dropdown) work ?

**Comment by patrickmros** [comment]
Yes, it's working without boost! I checked it because you wrote it will significantly improve the results. Does that mean i now have inferior results?

**Comment by thygate** [comment]
>DepthMap v0.2.6

pull latest version.

**Comment by thygate** [comment]
boost will generate the best results, see observations under usage in the readme.

boost cpu support is experimental at this time.

**Comment by patrickmros** [comment]
> > DepthMap v0.2.6
> 
> pull latest version.

Tried it before you mentioned it. First thing i should have done. But in v0.2.8 the problem still persists.

**Comment by patrickmros** [comment]
> error message, stack trace, parameters, .. ?

same as before!

`DepthMap v0.2.8
device: cpu
Loading model weights from  ./models/midas/dpt_large-midas-2f21e586.pt
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing depthmap(s) ..
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=768x1024 at 0x29EC8FD1120>, None, '', '', 1, 0, 1200, 1200, False, False, True, True, True, False, True, 1) {}
Traceback (most recent call last):
  File "J:\sd_06_10_2022\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "J:\sd_06_10_2022\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "J:\sd_06_10_2022\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 399, in run_generate
    outputs = run_depthmap(None, outpath, imageArr, imageNameArr, compute_device, model_type, net_width, net_height, match_size, invert_depth, boost, save_depth, show_depth, show_heat, combine_output, combine_output_axis)
  File "J:\sd_06_10_2022\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 253, in run_depthmap
    prediction = estimateboost(img, model, model_type, pix2pixmodel)
  File "J:\sd_06_10_2022\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 1093, in estimateboost
    whole_image_optimal_size, patch_scale = calculateprocessingres(img, net_receptive_field_size, r_threshold_value, scale_threshold, whole_size_threshold)
  File "J:\sd_06_10_2022\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 693, in calculateprocessingres
    grad_region = cv2.dilate(grad_resized, kernel2, iterations=1)
UnboundLocalError: local variable 'grad_resized' referenced before assignment`

**Comment by patrickmros** [comment]
Sorry, just to make it clear: it's working without boost but not with boost, even with the newest version.

**Comment by thygate** [comment]
ok that now narrows it down, I will have to investigate further, as things apparently went south before the error in that trace.

You don't have a cude gpu in this machine ?

**Comment by patrickmros** [comment]
Yes, the res101 network is working on cpu without boost.

My GPU is a RTX3060 and the CPU is an AMD Ryzen 5 2600X.

**Comment by thygate** [comment]
If I may ask, why use CPU mode when you have a cuda capable card ?

**Comment by patrickmros** [comment]
I tried to get the highest resolution possible. The 3060 only has 12GB VRAM. That's not enough for 1500 x 1500 px. For lower resolution i use the GPU.

**Comment by thygate** [comment]
I can generate 2048x2048 sd images on a 8GB card .. 

For depthmaps, dpt_* do require a lot more vram, res101 has no problem.

I'm really not sure why you get that error, that variable it's complaining about is initialized in the block above it with known good values .. I'm thinking maybe package conflict or something, so hence the question if there's anything special about your python environment ?

**Comment by thygate** [comment]
I'm considering this issue solved, please open a new issue if problems persist.
