### ISSUE TITLE
Output PNGs?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [thygate/stable-diffusion-webui-depthmap-script#430]
Firstly this tool is awesome!
It would be really great if we could output a png sequence instead of an mp4 though.  Basically I'm trying to output a left and right stereo pair with this wonderful in-painting, but I'm having to do a hacky workaround by using the "generate video" tab and setting it to "dolly" and only translating it on the x axis.  It would be fantastic if there were a better way to output a stereo pair with this amazing inpainting.

**Comment by semjon00** [comment]
@noobtoob4lyfe 

You can use ffmpeg to split the video into frames and then do batch processing. Make sure to use a powerful model like ZoeDepth or Depth Anything, otherwise you will have a lot of jittering between frames.

Hope it helps (somebody)

**Comment by semjon00** [comment]
Should document all this
