### ISSUE TITLE
How does "match net size to input size" work? 

### ISSUE THREAD

**Issue by noobtoob4lyfe** [thygate/stable-diffusion-webui-depthmap-script#434]
I'm using DepthAnthing with the "match net size to input size" checkbox enabled and the depth it generates is very good.  I would like like know exactly what net height and width values get use with that option.  I'm asking because if I manually set the net width and height to match my input image dimension (1080p) it takes much longer to process than if I use "match net size to input size".   How is that "net size" calculated when "match net size to input size" is enabled?

**Comment by semjon00** [comment]
Better documentation needed....
Match size is to ensure that image effective size matches the image size (height and width). Useful to set to false if depthmaps are weird, useful to set to true if they need to be sharper. Could have been a "match resolution" button, but current impl. plays well with batch processing.
