### ISSUE TITLE
Error loading the depth map script

### ISSUE THREAD

**Issue by knordest** [thygate/stable-diffusion-webui-depthmap-script#435]
Hi, I am very new to stable diffusion web ui and I managed to install it and make it run by watching some tutorials on youtube. I discovered the depth map extension and wanted to use it to create pointcloud like visuals inside of TouchDesigner. But unfortunately, everytime I boot the Automatic1111 web ui, it shows "Error loading script: depthmap_api.py".
<img width="1618" alt="Screenshot 2024-05-02 at 11 47 49 PM" src="https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/168771618/7a233de3-7875-45fb-b3a0-0bc61bd175d0">

what could be the possible solution for this? Please help me out and thank you so much!

**Comment by larinius** [comment]
Same here, it just a sourse of endless bugs, I added several packages, and installed an outdated jax bot this pile of software still has a lot more bugs and refuses to start. The best solution is just to delete and forget this crap.

**Comment by semjon00** [comment]
I think it should be fixed by now @larinius @knordest could you please test?
