### ISSUE TITLE
Cannot download `edge_model.pth` for inpainted mesh

### ISSUE THREAD

**Issue by nolanblew** [thygate/stable-diffusion-webui-depthmap-script#442]
Just installed fresh, and when trying to generate the inpainted 3d-mesh, it attempts to download `edge_model.pth` from https://filebox.ece.vt.edu/~jbhuang/project/3DPhoto/model/edge-model.pth. However, that URL no longer exists and returns a 404, so the generation fails.

**Comment by HB00** [comment]
> edge-model.pth

I am also unable to download. I found that you can try manually downloading from another download address and then move to the specified location.
[](https://huggingface.co/spaces/Epoching/3D_Photo_Inpainting/tree/e389e564fd2a55cfa4582be8c8239295d102aebd/checkpoints)
