### ISSUE TITLE
AttributeError: 'Processed' object has no attribute 'scheduler' / No longer working again in A1111 V1.9.3 

### ISSUE THREAD

**Issue by LVNSDCAPE** [thygate/stable-diffusion-webui-depthmap-script#443]
Steroscopic output, side by side / left right /
GPU selected ( I have a RTX 3080 )

version: [v1.9.3]  •  python: 3.10.9  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2

Resulting depthmap resolution will be : (1536, 1024)
patches to process: 14
         processing patch 0 / 13 | [ 92 362 714 714]
         processing patch 1 / 13 | [227 362 714 714]
         processing patch 2 / 13 | [106 241 687 687]
         processing patch 3 / 13 | [254 254 660 660]
         processing patch 4 / 13 | [147 551 605 605]
         processing patch 5 / 13 | [282 551 605 605]
         processing patch 6 / 13 | [188 188 523 523]
         processing patch 7 / 13 | [323 188 523 523]
         processing patch 8 / 13 | [350 754 469 469]
         processing patch 9 / 13 | [229  94 441 441]
         processing patch 10 / 13 | [108 377 414 414]
         processing patch 11 / 13 | [512 377 414 414]
         processing patch 12 / 13 | [   0 1079  360  360]
         processing patch 13 / 13 | [539 539 360 360]
*** Error completing request

 Traceback (most recent call last):
      File "D:\SD-Portable-1.9\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\SD-Portable-1.9\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\SD-Portable-1.9\modules\txt2img.py", line 106, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
      File "D:\SD-Portable-1.9\modules\scripts.py", line 773, in run
        processed = script.run(p, *script_args)
      File "D:\SD-Portable-1.9\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 57, in run
        info = create_infotext(
      File "D:\SD-Portable-1.9\modules\processing.py", line 774, in create_infotext
        "Schedule type": p.scheduler,
    AttributeError: 'Processed' object has no attribute 'scheduler'

**Comment by hoagiemc** [comment]
I have the same issue, using txt2image.


Startup time: 35.7s (prepare environment: 13.8s, import torch: 8.3s, import gradio: 1.4s, setup paths: 2.3s, initialize shared: 0.5s, other imports: 1.3s, load scripts: 5.7s, initialize extra networks: 0.2s, create ui: 1.4s, gradio launch: 0.6s).
Applying attention optimization: Doggettx... done.
Model loaded in 10.7s (load weights from disk: 0.2s, create model: 0.8s, apply weights to model: 9.2s, calculate empty prompt: 0.2s).
100%|##########| 20/20 [00:04<00:00,  4.86it/s]
DepthMap v0.4.6 (7a3a7820)#####| 20/20 [00:03<00:00,  6.19it/s]
device: cuda
Loading model(s) ..
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing output(s) ..
  0%|          | 0/1 [00:00<?, ?it/s]*** Error completing request
*** Arguments: ('task(0vg4r44tluepln0)', <gradio.routes.Request object at 0x0000027E25B37190>, 'white sportscar', '', [], 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 5, 20, 'DPM++ 2M', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), None, False, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CUDA', False, 0, 'None', '', None, False, False, 0.5, 0, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50, True, False, 0, 'Range', 1, 'GPU', True, False, False, False, True, 0, 448, False, 448, False, False, 3, False, 3, True, 3, False, 'Horizontal', False, False, 'u2net', False, True, True, False, 0, 2.5, 'polylines_sharp', ['left-right'], 2, 0, '\u222fboost\u222fclipdepth\u222fclipdepth_far\u222fclipdepth_mode\u222fclipdepth_near\u222fcompute_device\u222fdo_output_depth\u222fgen_normalmap\u222fgen_rembg\u222fgen_simple_mesh\u222fgen_stereo\u222fmodel_type\u222fnet_height\u222fnet_size_match\u222fnet_width\u222fnormalmap_invert\u222fnormalmap_post_blur\u222fnormalmap_post_blur_kernel\u222fnormalmap_pre_blur\u222fnormalmap_pre_blur_kernel\u222fnormalmap_sobel\u222fnormalmap_sobel_kernel\u222foutput_depth_combine\u222foutput_depth_combine_axis\u222foutput_depth_invert\u222fpre_depth_background_removal\u222frembg_model\u222fsave_background_removal_masks\u222fsave_outputs\u222fsimple_mesh_occlude\u222fsimple_mesh_spherical\u222fstereo_balance\u222fstereo_divergence\u222fstereo_fill_algo\u222fstereo_modes\u222fstereo_offset_exponent\u222fstereo_separation') {}
    Traceback (most recent call last):
      File "C:\Users\XXXXXXX\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\XXXXXXX\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\XXXXXXX\stable-diffusion\stable-diffusion-webui\modules\txt2img.py", line 106, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
      File "C:\Users\XXXXXXX\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 773, in run
        processed = script.run(p, *script_args)
      File "C:\Users\XXXXXXX\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 57, in run
        info = create_infotext(
      File "C:\Users\XXXXXXX\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 774, in create_infotext
        "Schedule type": p.scheduler,
    AttributeError: 'Processed' object has no attribute 'scheduler'

**Comment by SirNate0** [comment]
Fix: Replace the first parameter of `create_infotext()` with `p` instead of `processed` in `stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py`
