### ISSUE TITLE
How do I add new models?

### ISSUE THREAD

**Issue by metahades18892** [thygate/stable-diffusion-webui-depthmap-script#447]
I downloaded more updated models, I put them in the corresponding folders within "models", but it does not recognize it when I open the Depth TAP

![imagen](https://github.com/thygate/stable-diffusion-webui-depthmap-script/assets/163777886/ee5d3501-4aa7-4436-aec3-a96e916b1ab1)

**Comment by semjon00** [comment]
Depth Anytjing can be used from the interface. Automatic model rexognition is not supported.

[Needs documentation]

**Comment by metahades18892** [comment]
> Hello!
> 
> Depth Anytjing can be used from the interface. Automatic model rexognition is not supported.
> 
> [Needs documentation]

I don't understand, so it can't read models other than the ones that come by default with this extension?

**Comment by semjon00** [comment]
Yes.

You dont need to manyally download these, they will be downloaded automatically on the first use
