### ISSUE TITLE
No module named 'inpaint'

### ISSUE THREAD

**Issue by axymeus** [thygate/stable-diffusion-webui-depthmap-script#453]
Works when generating stereoscopic images, but fails with error below when trying to generate 3D inpainted mesh. Using A1111 1.7.0.

DepthMap v0.4.7 (1e92b5f2)
device: cuda
Loading model(s) ..
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing output(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]wholeImage being processed in : 896
Adjust factor is: 2.0405783582089554
Selecting patches ...
Target resolution:  (3657, 2845, 3)
Resulting depthmap resolution will be : (1152, 896)
patches to process: 33
         processing patch 0 / 32 | [ 35  35 856 856]
         processing patch 1 / 32 | [ 35 141 856 856]
         processing patch 2 / 32 | [ 35 247 856 856]
         processing patch 3 / 32 | [ 96 413 733 733]
         processing patch 4 / 32 | [  0   0 712 712]
         processing patch 5 / 32 | [  0 106 712 712]
         processing patch 6 / 32 | [  0 212 712 712]
         processing patch 7 / 32 | [  0 318 712 712]
         processing patch 8 / 32 | [  0 423 712 712]
         processing patch 9 / 32 | [106   0 712 712]
         processing patch 10 / 32 | [242  30 651 651]
         processing patch 11 / 32 | [242 136 651 651]
         processing patch 12 / 32 | [242 242 651 651]
         processing patch 13 / 32 | [312 524 507 507]
         processing patch 14 / 32 | [  5 217 487 487]
         processing patch 15 / 32 | [  5 323 487 487]
         processing patch 16 / 32 | [  5 428 487 487]
         processing patch 17 / 32 | [  5 534 487 487]
         processing patch 18 / 32 | [217   5 487 487]
         processing patch 19 / 32 | [323   5 487 487]
         processing patch 20 / 32 | [449  25 446 446]
         processing patch 21 / 32 | [449 131 446 446]
         processing patch 22 / 32 | [373 479 385 385]
         processing patch 23 / 32 | [ 86 192 323 323]
         processing patch 24 / 32 | [ 86 827 323 323]
         processing patch 25 / 32 | [192 827 323 323]
         processing patch 26 / 32 | [297 827 323 323]
         processing patch 27 / 32 | [403 827 323 323]
         processing patch 28 / 32 | [  0 318 282 282]
         processing patch 29 / 32 | [  0 529 282 282]
         processing patch 30 / 32 | [  0 635 282 282]
         processing patch 31 / 32 | [423   0 282 282]
         processing patch 32 / 32 | [529   0 282 282]
100%|█████████████████████████████████████| 1/1 [00:12<00:00, 12.84s/it]
Computing output(s) done.
No module named 'inpaint', some issue with generating inpainted mesh
All done.

**Comment by Five-Birds** [comment]
I have the same error.

**Comment by Five-Birds** [comment]
DepthMap v0.4.7 (1e92b5f2)
device: cuda
Loading model(s) ..
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
Computing output(s) ..
  0%|                                                                                              | 0/1 [00:00<?, ?it/s]wholeImage being processed in : 1568
Adjust factor is: 1.0
Selecting patches ...
Target resolution:  (1758, 3136, 3)
Resulting depthmap resolution will be : (2595, 4629)
patches to process: 14
         processing patch 0 / 13 | [ 992    0 2315 2315]
         processing patch 1 / 13 | [1488    0 2315 2315]
         processing patch 2 / 13 | [1984    0 2315 2315]
         processing patch 3 / 13 | [1228  732 1842 1842]
         processing patch 4 / 13 | [1724  732 1842 1842]
         processing patch 5 / 13 | [2220  732 1842 1842]
         processing patch 6 / 13 | [2716  732 1842 1842]
         processing patch 7 / 13 | [ 779  283 1748 1748]
         processing patch 8 / 13 | [ 449  449 1417 1417]
         processing patch 9 / 13 | [ 496    0 1323 1323]
         processing patch 10 / 13 | [ 992    0 1323 1323]
         processing patch 11 / 13 | [1488    0 1323 1323]
         processing patch 12 / 13 | [1984    0 1323 1323]
         processing patch 13 / 13 | [2976  496 1323 1323]
100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:20<00:00, 20.00s/it]
Computing output(s) done.
No module named 'inpaint', some issue with generating inpainted mesh
All done.

**Comment by semjon00** [comment]
@axymeus @Five-Birds I can't reproduce the issue. Could you please provide more info on your environment - do you use standalone more or WebUI mode? What version of WebUI?

**Comment by axymeus** [comment]
As stated, I'm using Automatic 1111 v1.7.0, ran installation through the "install via URL" in extensions tab and reloaded.

**Comment by semjon00** [comment]
@axymeus Did you restart it, too, or just reloaded?

**Comment by axymeus** [comment]
Both. I'm still getting this error today after a complete reboot.

**Comment by semjon00** [comment]
Thanks! Ok.... I've got one lead. Be right back...

**Comment by semjon00** [comment]
I made the fix, hopefully it works now. Please update and test

**Comment by semjon00** [comment]
@axymeus

**Comment by axymeus** [comment]
Fixed on my end.

**Comment by semjon00** [comment]
@axymeus Great! Thank you for helping me
