### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.call_queue' 

### ISSUE THREAD

**Issue by MabrurHrivu** [thygate/stable-diffusion-webui-depthmap-script#46]
I get this error while launching automatic1111 webui and the script doesn't load:

Error loading script: depthmap.py
Traceback (most recent call last):
  File "D:\Super stable diffusion 2.0\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\Super stable diffusion 2.0\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\Super stable diffusion 2.0\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 8, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, wrap_gradio_call
ModuleNotFoundError: No module named 'modules.call_queue'

Can you help me out?

**Comment by thygate** [comment]
That's strange, did you try restarting the backend after install ?

**Comment by MabrurHrivu** [comment]
I did, always the same error. The script never even showed up in the list where it's supposed to

**Comment by thygate** [comment]
Are you up to date with the latest version of the webui ?

Is there anything special about your python environment ?

I have no clue why it would not find that module, it's in the ./modules directory for a normal install.

**Comment by MabrurHrivu** [comment]
I don't see a file called call_queue.py in my folder. I'll try getting a fresh install. I'll let you know what happens.

**Comment by thygate** [comment]
Very strange, functions in that module are used all over, so i can't imagine your setup working at all without it..

**Comment by MabrurHrivu** [comment]
It works now. My automatic1111 was a bit out of date. Thanks for helping me out.
