### ISSUE TITLE
[BUG] This extension's depth_anything_v2 implementation breaks its import in sd-webui-controlnet

### ISSUE THREAD

**Issue by DominikDoom** [thygate/stable-diffusion-webui-depthmap-script#463]
sd-webui-controlnet semi-recently added support for depth_anything_v2 in https://github.com/Mikubill/sd-webui-controlnet/commit/648025ba6bc99df175d896a6aaf793cf72574b1c.

However, if this extension is also installed and comes after it in the load order, trying to use depth_anything_v2 in controlnet causes a `No module named 'depth_anything_v2.dpt` error (see issue https://github.com/Mikubill/sd-webui-controlnet/issues/3018).

The reason for this is that depthmap-script ships with a copy of the code instead of installing it from a wheel or requirements.txt like it should, and since the depth_anything_v2 folder contains its own \_\_init.py\_\_, the module reference gets overwritten.

Deleting the whole `depthmap-script/depth_anything_v2` subfolder fixes it.
~If depth_anything_v2 was properly installed into the venv by controlnet already, this doesn't even break the reference here, it will just import that version instead of the local copy since the import isn't relative. From what I could observe, this causes no difference in functionality for depthmap-script.~ EDIT: Not entirely correct since it needed a modification to the `__init__.py` / import which I forgot I did during experimenting. So just renaming like proposed will be better.

sd-webui-controlnet installs v2 from this wheel:
```py
try_install_from_wheel(
    "depth_anything_v2",
    wheel_url=os.environ.get(
        "DEPTH_ANYTHING_V2_WHEEL",
        "https://github.com/MackinationsAi/UDAV2-ControlNet/releases/download/v1.0.0/depth_anything_v2-2024.7.1.0-py2.py3-none-any.whl",
    ),
)
```
This extension should do the same and remove the local copy or at least modify it to not conflict.

**Comment by graemeniedermayer** [comment]
Thanks! This is how we previously resolved this type of issue.
https://github.com/thygate/stable-diffusion-webui-depthmap-script/commit/06cd46ea82ac5852748396f0fc56cb9152cda4c2

Historically our solution is to make the files `ddepth_anything` by adding a `d`. So that would be a quick fix. We might want to do this for marigold too.

I have a preference for local copies. Local copies have been much easier to maintain. These repos use similar dependencies, so one repo updating can easily break the other repos.

**Comment by DominikDoom** [comment]
That's also true, in the end it just comes down to webui regrettably not having proper isolation for extensions. If you want to keep the local copy for maintainability, renaming is definitely the easiest fix.

This isn't really related to the issue, but the local copy still has a lot of unnecessary files in that case - depthmap-script only imports the main DepthAnythingV2 definition referenced in https://github.com/thygate/stable-diffusion-webui-depthmap-script/blob/main/depth_anything_v2/__init__.py if I didn't miss anything in the code.
The whole rest here seems to come from the original repo: 
![image](https://github.com/user-attachments/assets/16670ee1-3254-464b-81a3-4f2f8836d0fd)
and could be removed, right?
