### ISSUE TITLE
Midas Repository Not Found

### ISSUE THREAD

**Issue by Frigate19** [thygate/stable-diffusion-webui-depthmap-script#48]
I am getting this error when trying to launch this extension:

`Error loading script: depthmap.py
Traceback (most recent call last):
  File "A:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
  File "A:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "A:\Stable Diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 32, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'repositories.midas'`

When I installed the extension, it successfully put both midas and BoostingMonocularDepth into the /repositories folder, so it's not like midas is missing entirely. However, I am running this entire thing on a drive that is apparently not formatted to be able to track ownership. So I had some issues when I was first installling the webui where I ended up using the command "git config --global --add safe.directory '*'" to avoid having to manually set ownership of every folder. I'm wondering if that's connected. But I haven't run into any other issues after using that command until now.

**Comment by thygate** [comment]
Did you restart the backend ?

Also, all dependencies are installed automatically now with the extension.
You should have /stable-diffusion-webui/repositories/midas/

**Comment by Frigate19** [comment]
Oops. Restarting the backend instead of using the restart button inside the ui fixed it. That's what I get for being lazy. Thank you for the quick response

**Comment by thygate** [comment]
You're welcome, easy fix, have fun =)
