### ISSUE TITLE
Error loading script: depthmap.py

### ISSUE THREAD

**Issue by yampy** [thygate/stable-diffusion-webui-depthmap-script#55]
Hello. I installed the script according to the instructions, but when I run webui, I get the following error and cannot use it. Is there anything I should try?

```
Error loading script: depthmap.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\stable-diffusion-webui-master\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\stable-diffusion-webui-master\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 33, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "C:\stable-diffusion-webui\stable-diffusion-webui-master\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "C:\stable-diffusion-webui\stable-diffusion-webui-master\repositories\midas\midas\blocks.py", line 21, in <module>
    from .backbones.next_vit import (
  File "C:\stable-diffusion-webui\stable-diffusion-webui-master\repositories\midas\midas\backbones\next_vit.py", line 8, in <module>
    file = open("./externals/Next_ViT/classification/nextvit.py", "r")
FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/classification/nextvit.py'
```

**Comment by thygate** [comment]
I see the midas repo was recently updated, another user also reported this error on a new install, and has a fix
See https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/41#issuecomment-1364598195

I will look into it ..

**Comment by GruvoSmack** [comment]
> The commit hash for the midas repo i have installed is 66882994a432727317267145dc3c2e47ec78c38a I've changed the hash in [install.py](http://install.py) to b845b7839c89567c123b06dddfff8d5e708834b7 which is much more recent, so confirmation of this working is welcome =)

Still getting the same error after following procedure and updating.

**Comment by yampy** [comment]
Unfortunately, same as above comment. 
I cloned the webui project again and tried from the beginning and I am getting the same error.

Now I will try to solve this problem by manually clone nextvid and modify midas\backbones\next_vit.py.

**Comment by thygate** [comment]
I've changed the hash in install.py to the same one I have at the moment.

Please delete those two folders and reinstall again, it should clone a working midas copy now.

**Comment by yampy** [comment]
Thanks for the really quick response.
But for some reason the above fixes did not solve the problem in my environment.

However, I did the following and it worked fine!

1. clone Next_ViT from github（https://github.com/bytedance/Next-ViT）
2. put the project folder into "C:\stable-diffusion-webui-master\repositories\midas\midas\externals"
3. modify "C:\stable-diffusion-webui-master\repositories\midas\midas\backbones\next_vit.py" line 8 to 10.

```
path = r"C:\stable-diffusion-webui-master\repositories\midas\midas\externals\Next_ViT\classification\nextvit.py"
file = open(path, "r")
source_code = file.read().replace(" utils", ".. externals.Next_ViT.classification.utils")
```

It's not beautiful way because it's not a fundamental solution, but I'm glad it works anyway. 
The code you provided is great. Thank you so much.

@thygate If you don't mind, I would like to close this Issue.

**Comment by thygate** [comment]
I was hoping to solve it by going to an earlier commit for the midas repo, the current commit hash is known to be working, I assume the git_clone in install.py is ignoring the hash, I can't test it myself at this time, so sorry for the multiple tries, and thanks for verifying. 

For others reading this, you can also manually clone the midas repo into /repositories/midas with the commit hash mentioned above (66882994a432727317267145dc3c2e47ec78c38a).

I will be implementing support for midas 3.1 asap, bringing a permanent fix.

It might be helpful to others to leave the issue open until a permanent fix is in place ..

**Comment by amerqad** [comment]
> Thanks for the really quick response. But for some reason the above fixes did not solve the problem in my environment.
> 
> However, I did the following and it worked fine!
> 
> 1. clone Next_ViT from github（[https://github.com/bytedance/Next-ViT）](https://github.com/bytedance/Next-ViT%EF%BC%89)
> 2. put the project folder into "C:\stable-diffusion-webui-master\repositories\midas\midas\externals"
> 3. modify "C:\stable-diffusion-webui-master\repositories\midas\midas\backbones\next_vit.py" line 8 to 10.
> 
> ```
> path = r"C:\stable-diffusion-webui-master\repositories\midas\midas\externals\Next_ViT\classification\nextvit.py"
> file = open(path, "r")
> source_code = file.read().replace(" utils", ".. externals.Next_ViT.classification.utils")
> ```
> 
> It's not beautiful way because it's not a fundamental solution, but I'm glad it works anyway. The code you provided is great. Thank you so much.
> 
> @thygate If you don't mind, I would like to close this Issue.

Great, my problem has been sovled, thanks mate

**Comment by thygate** [comment]
easiest solution here : https://github.com/thygate/stable-diffusion-webui-depthmap-script/discussions/63#discussioncomment-4499155

**Comment by thygate** [comment]
permanent fix will soon be in place, will upgrade to midas 3.1 asap, meanwhile please use instructions above if you still have this problem.

**Comment by thygate** [comment]
Should be fixed in latest version.
