### ISSUE TITLE
Use in Extras

### ISSUE THREAD

**Issue by jnpatrick99** [thygate/stable-diffusion-webui-depthmap-script#6]
Wow, this is awesome!

Is there a way to use it in "Extras" on already existing images?
Thank you!

**Comment by thygate** [comment]
For now you could use img2img and set denoising strength to zero to basically copy the input image without changing it ..
I'm looking into possibilities for adding the option to do existing images ..
Maybe make the script into an extension ...

Keep watching the repo, I will add some other options too later.

Thanks.
