### ISSUE TITLE
Missing .\models\3DPhoto folder by default

### ISSUE THREAD

**Issue by mykeehu** [thygate/stable-diffusion-webui-depthmap-script#76]
In version 0.3.4, I checked the _Generate 3D inpainted mesh and demo videos. (Sloooow)_ option at the bottom. After generating the depthmap I got errors, and then I noticed that the first model could not be downloaded because the 3DPhoto folder did not exist in the models directory. After creating this manually, the generation was running.
This should be fixed in the script, so that if there is no such folder, it is created before the 3Dphoto models is downloaded.

**Comment by thygate** [comment]
You are absolutely right, I forgot about that, I just fixed it !

**Comment by Tekashi69ine** [comment]
> In version 0.3.4, I checked the _Generate 3D inpainted mesh and demo videos. (Sloooow)_ option at the bottom. After generating the depthmap I got errors, and then I noticed that the first model could not be downloaded because the 3DPhoto folder did not exist in the models directory. After creating this manually, the generation was running. This should be fixed in the script, so that if there is no such folder, it is created before the 3Dphoto models is downloaded.

pls explain how
