### ISSUE TITLE
RuntimeWarning: divide by zero encountered in divide   input_disp = 1./np.abs(input_depth)

### ISSUE THREAD

**Issue by LockMan007** [thygate/stable-diffusion-webui-depthmap-script#77]
Generating inpainted mesh .. (go make some coffee) ..
WARNING:py.warnings:D:\ai\a1\extensions/stable-diffusion-webui-depthmap-script/scripts\inpaint\mesh_tools.py:174: RuntimeWarning: divide by zero encountered in divide
  input_disp = 1./np.abs(input_depth)

**Comment by thygate** [comment]
safe to ignore, but probably means the depthmap was all black .. right?

**Comment by LockMan007** [comment]
> 

I don't know, just reporting an error message, I'm new to this one.
Works pretty cool. Thanks.

**Comment by thygate** [comment]
I chose not to ignore that warning since it usually means something is wrong with the depthmap ..

I'm closing this since there is no error, but thanks for reporting, don't hesitate to report any problems ..
