### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by semjon00** [thygate/stable-diffusion-webui-depthmap-script#79]
Hello! Thank you for 0.3.1, I had quite a demo effect when I tried to show this cool plugin to my friend and it just refused to work because midas broke. It may be helpful to specify the origin of source files and maybe add their LICENSE files (just in case).

**Comment by thygate** [comment]
Ah, I totally forgot about licensing since it started out without including any 3rd party code/repositories in this repository ..

I'm tempted to just drop in the MIT license, what do you think ?

**Comment by thygate** [comment]
Only just noticed the leres Adobe Research license ... not sure how to satisfy it .. suggestions/help appreciated ..

**Comment by semjon00** [comment]
@thygate :+1: MIT is a good choice

Uhh, there are original licenses, then licenses of derivatives (BoostingMonocularDepth), then the GitHub ToS... it gets very confusing, much harder than I thought.

There is a function of "portals" (?) in GitHub, but I don't know how it works. You can see an example [here](https://github.com/ValveSoftware/Proton). Not sure whether using something like this changes anything.

Here is one thing I found. GitHub ToS D 5 emplies that we can `use, display, and perform [content] through the GitHub Service and to reproduce [content] solely on GitHub as permitted through GitHub's functionality`. However, (maybe) it does not allow using the code locally ([these commas all over again](https://proofed.com/writing-tips/5-expensive-comma-typos-history/)). However, [pix2pix license](https://github.com/phillipi/pix2pix/blob/master/LICENSE) allows us to do that, `provided that the following conditions are met: [...] Redistributions of source code must retain the above copyright notice, [...] list of conditions and the [...] disclaimer`. In one sentence: it is all confusing and adding the licenses will not harm.

**Comment by AugmentedRealityCat** [comment]
Just do as Automatic1111 is doing: **don't bother**. 

In one sentence: it is all confusing and licensing your extension in any official manner will just add to the confusion. 

You won't gain any new right, you won't make any new money, and licence freaks will never be pleased anyways.

**Comment by semjon00** [comment]
Well, Automatic1111 added the licenses of other projects just a couple of days ago ([82cfc22](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/82cfc227d735c140447d5b8dca29a71ee9bde127)), hence my issue. Dropping MIT into the project root is straightforward, and folks on webui discussions were largely supporting the idea of adding a project license.

**Comment by thygate** [comment]
I will drop a MIT license in the repo root later today, and drop the adobe research license into the /lib (leres) folder.
