### ISSUE TITLE
img2img / anaglyph stopped working in automatic1111

### ISSUE THREAD

**Issue by drixOps** [thygate/stable-diffusion-webui-depthmap-script#80]
hi there,
I did a lot of generation today and they worked perfecty, but now I am getting this error when generating an anaglyph red-cyan image from img2img in automatic1111 with this error: 

AttributeError: 'numpy.ndarray' object has no attribute 'save'

img2img with side-by-side works, txt2img also still works (also with red/cyan). 

did I miss something?
thanks in advance
best d
PS: thanks for this amazing tool!!!

**Comment by drixOps** [comment]
thanks a lot for your time and your testing! It only happens, when I use a custom output dir. If I leave this tab blank, it works perfectly. thanks again!

**Comment by thygate** [comment]
where do you set the custom output path ?
