### ISSUE TITLE
Option to flip left-right images when generating stereo

### ISSUE THREAD

**Issue by shadodo76** [thygate/stable-diffusion-webui-depthmap-script#82]
If I want to see the images by crossing my eyes, instead of a 3D device (such as VR headset), the left and right images are in the wrong position.

It would be neat, and probably very easy for you, to have the option to flip the left and right images when the stereogram is saved.

**Comment by thygate** [comment]
I added it as a setting, Go to the webui settings, find the depthmap section, and there you can enable "Flip Left/Right in SBS stereo images (requested for cross-eyed viewing)"

**Comment by shadodo76** [comment]
I have updated, it now effectively says v0.3.7 but I can't locate the Flip option.
![image](https://user-images.githubusercontent.com/61641856/211769373-88c73683-2e07-4408-a633-6cb19f9991ea.png)

**Comment by shadodo76** [comment]
Thanks. It works.
