### ISSUE TITLE
Run Google Colab?

### ISSUE THREAD

**Issue by SmartCardEc** [thygate/stable-diffusion-webui-depthmap-script#9]
<img width="701" alt="Screenshot 2022-11-04 at 15 19 50" src="https://user-images.githubusercontent.com/104737172/200067028-9e5173dd-9b9d-4053-b81d-f75f6ffd0587.png">

how cai i run in google colab?

**Comment by thygate** [comment]
You can run the MiDaS network on its own using their colab, linked here : https://pytorch.org/hub/intelisl_midas_v2/

direct link: (https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/intelisl_midas_v2.ipynb)
