### ISSUE TITLE
[Request] add option to load custom depthmap image for inpaint 3D

### ISSUE THREAD

**Issue by tazzkiller** [thygate/stable-diffusion-webui-depthmap-script#92]
this would require loading an adjusted mask under other editing software

**Comment by AugmentedRealityCat** [comment]
There is a script that does that:
https://github.com/AnonymousCervine/depth-image-io-for-SDWebui 
I've tested it over the last few days and it works very well so far.
It also gives you the opportunity to save the depthmap that the 2.0 depth model uses internally when you use it without your own custom depthmap.
Have fun !

**Comment by SimonBuysse** [comment]
> There is a script that does that: https://github.com/AnonymousCervine/depth-image-io-for-SDWebui I've tested it over the last few days and it works very well so far. It also gives you the opportunity to save the depthmap that the 2.0 depth model uses internally when you use it without your own custom depthmap. Have fun !

Can you explain to me how you use this with depthmap stable diffusion, I see the script active in txt2img etc but there is no script dropdown for this extension.

**Comment by AugmentedRealityCat** [comment]
> Can you explain to me how you use this with depthmap stable diffusion,

I misunderstood your first request. I thought you wanted to use the inpaint function with the depth-map 2.0 model and feed it a custom depthmap. But I understand that what you really wanted was the option to use a custom depthmap for the 3d-photo-inpainting function of the depthmap extension itself. 
The code as implemented in the extension doesn't allow for that as far as I know.
Your best bet would be to install the standalone version of the [3d-photo-inpainting repo](https://github.com/vt-vl-lab/3d-photo-inpainting). @donlinklok even made [a version that runs on windows](https://github.com/donlinglok/3d-photo-inpainting). In the settings it's possible to [turn off Midas Depth detection](https://github.com/vt-vl-lab/3d-photo-inpainting/blob/de0446740a3726f3de76c32e78b43bd985d987f9/argument.yml#L26), and [to change the depthmap input](https://github.com/vt-vl-lab/3d-photo-inpainting/blob/de0446740a3726f3de76c32e78b43bd985d987f9/argument.yml#L25) from the default format in python data (.npy) to PNG instead, and put your picture where their own example is (It's a scene on the Moon if I remember correctly).

**Comment by SimonBuysse** [comment]
Thank you AugmentedRealityCat, that is indeed what I was looking for, I will test it out.
I make my own depthmaps in photoshop and really put effort to reduce artifacting.

**Comment by AugmentedRealityCat** [comment]
Come back to show us how it goes. 

Are you using Photoshop's Neural filters to estimate the depthmaps first ? I do not have the latest version of Photoshop (still using the last version you could actually buy, CS6) but I've heard there was such a feature.

**Comment by semjon00** [comment]
Custom depthmaps are currently supported by the program.
