### ISSUE TITLE
Error: The size of tensor a (135) must match the size of tensor b (136) at non-singleton dimension 2

### ISSUE THREAD

**Issue by sashaok123** [thygate/stable-diffusion-webui-depthmap-script#98]
When starting the generation, an error occurs: "The size of tensor a (135) must match the size of tensor b (136) at non-singleton dimension 2".
<img width="860" alt="image" src="https://user-images.githubusercontent.com/27728380/213964915-04d52d40-80e6-454b-9128-aeae2b66f10f.png">

Version: DepthMap v0.3.8

Settings: 
<img width="620" alt="image" src="https://user-images.githubusercontent.com/27728380/213965114-c0931522-317f-4496-80e4-53b245768a0b.png">

python: 3.10.9  •  torch: 1.12.1+cu113  •  xformers: 0.0.14.dev  •  gradio: 3.16.2  •  commit: [c98cb0f8](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/c98cb0f8ecc904666f47684e238dd022039ca16f)  •  checkpoint: [685c1b4d00](https://google.com/search?q=685c1b4d00d5ffb8a2b2f47215c5e5bd44ef1d8f0948bbdd9d23cca9964b3623)

**Comment by sashaok123** [comment]
When using "BOOST (multi-resolution merging)" the error does not occur.

**Comment by sashaok123** [comment]
When choosing a different depth model, everything works the same way.
Only res101 does not work

**Comment by sashaok123** [comment]
Only 960x540

**Comment by graemeniedermayer** [comment]
There does appear to be a size restriction with res101. It gives a similar error with 512x513 so that's likely the source of the error.

**Comment by AugmentedRealityCat** [comment]
540 is not a standard Stable Diffusion resolution as it is not divisible by 64 - and in fact it's not even divisible by 32 or 16 or even 8, so I am not surprised this might be the cause of your problems right there.

**Comment by thygate** [comment]
Yes, there are no checks on input resolution. For instance when selecting "match input resolution", you could get this error.
Boost will always select valid resolutions.
